exports.language = function() {

	var arabic = {
		english : "English",

		turnOnGPS : "يرجى تفعيل نظام تحديد المواقع GPS",
		arabic : "عربي",
		loading : "تحميل ....",
		updating : "تحديث ...",
		cancel : "ألغاء",
		call : "مكالمة هاتفية",
		callConformAlert : 'هل أنت متأكد أنك تود إجراء مكالمة لـ',
		noCallAlert : 'خدمة الاتصال غير متوفرة',
		ok : "موافق",
		serviceError : 'الخدمة غير متوفرة حاليا. يرجى المحاولة لاحقا',
		doneTitle : "انتهى",
		// error : 'Error',
		error : 'خطأ',
		language : "تغيير اللغة",
		noInternet : "لا يوجد اتصال بالإنترنت",
		// networkError : "Network Error",
		networkError : "لا يوجد اتصال بالشبكة",
		appTitle : "تطبيقات الجمهور",
		exitConfirm : "هل أنت متأكد أنك تريد إغلاق التطبيق؟",
		yes : "نعم",
		no : "لا",
		invalidRoute : "مسار غير معرف",

		//Fb & Twitter msgs
		shareFBSuccess : "تمت مشاركة المحتوى على الفيسبوك بنجاح",
		shareTwitterSuccess : "تم نشر التغريدات في موقع تويتر بنجاح",
		shareFBFail : "لا يمكن المشاركة على الفيسبوك. الرجاء المحاولة لاحقا",
		shareTwitterFail : "لا يمكن المشاركة على التويتر. الرجاء المحاولة لاحقا",
		getTweetsFail : "لا يمكن جلب التغريدات. الرجاء المحاولة لاحقا ",
		duplicateMessage : "رسالة مكررة",
		facebookSuccessMessage : "تمت مشاركة المحتوى على الفيسبوك بنجاح",
		refNoTitle : "الرقم المرجعي",
		closeTitle : "أغلق",
		maximumImagesCountMsg : "وصلت الحد الأقصى لعدد الصور المسموح بها، الرجاء حذف بعض الصور",
		noAvailabliltyMsg : "عفوا، المطلوب غير متاح",

		//Form captions
		nameTitle : "الاسم",
		emailTitle : "البريد الالكتروني",
		emailOrPhoneTitle : "البريد الالكتروني أو الهاتف",
		typeTitle : "النوع",
		selectTypeTitle : "اختر النوع",
		selectSubTypeTitle : "اختر النوع الفرعي ",
		subjectTitle : "الموضوع",
		descriptionTitle : "الوصف",
		locationTitle : "الموقع",
		textBoxHintText : "النوع",
		textBoxHintText_Message : "ادخل الوصف",
		uploadImagesTitle : "ارفع صور ",
		saveTitle : "حفظ",
		submitTitle : "إرسال",
		cancelTitle : "إلغاء",
		resetTitle : "مسح",
		complaintSuccessMsg : "تم تقديم الشكوى بنجاح",
		helpdeskSuggestionSuccessMsg : "تم تقديم اقتراحك بنجاح",
		helpDeskTitle : "المساعدة",
		suggestionTitle : "اقتراح",

		//forms
		invalidEmailMsg : "البريد الالكتروني غير صحيح",
		enterValidEmailMsg : "أدخل بريد الكتروني صحيح",
		plzEnterMissingFieldsMsg : "يرجى تعبئة التالي",
		noInformationAvailableMsg : "لا توجد معلومات متاحة",

		//Camera module
		chooseImageSourceTitle : 'اختيار مصدر الصورة ...',
		cameraTitle : 'كاميرا',
		photoGalleryTitle : 'معرض الصور',
		noCameraMsg : 'ليس ثمة كاميرا في الجهاز',
		unexpectedErrorMsg : 'خطأ غير متوقع',

		//hint text for complaints and Help
		enterNameHint : 'أدخل الاسم ',
		enterEmailPhoneHint : 'أدخل البريد الالكتروني أو الهاتف ',
		enterSubjectHint : 'أدخل الموضوع',
		enterDescriptionHint : 'أدخل الوصف',

		register : "تسجيل",
		name : "الاسم",
		federalEntity : "الجهة الاتحادية",
		department : "الدائرة/القسم",
		email : "البريد الالكتروني ",
		emloyeeId : "البريد الالكتروني ",
		nationalIdCard : "بطاقة الهوية الوطنية",
		cancel : "إلغاء",
		//ok : "حسنا",

		taxVatTitle : "الشهادات الضريبية",
		takamulTitle : "تكامل",
		myBudgetTitle : "المحفظة الذكية",
		suppliersTitle : "خدمات الموردين",
		reportsTitle : "البيانات المالية المفتوحة",
		notificationsTitle : "الإشعارات",
		aboutMOFTitle : "عن الوزارة",
		contactMOFTitle : "تواصل مع الوزارة",
		myBudgetReportTitle : "تقرير ميزانيتي",
		newsTitle : "الأخبار والفعاليات",
		settingsTitle : "الإعدادات",
		takamulComingMsg : "Takamul is coming soon",
		//Budget
		budgetIndtroductionMsg : "تطبيق لمساعدتك في إنشاء وإدارة الميزانية الشخصية. \ سواء كنت محاسب ، أو ربة منزل أو طالب مدرسة، يمكنك استخدام التطبيق بسهولة وتتبع العديد من الميزانيات كما تريد.",
		instructionsTitle : "تعليمات",
		newBudgetTitle : "ميزانية الجديدة",
		existingBudget : "الميزانية الحالية",
		noBudgetMsg : "الميزانية الجديدة \n أضف ميزانية باستخدام '+'.",
		createBudgetTitle : "إضافة ميزانية جديدة",
		editBudgetTitle : "تعديل الميزانية ",
		nameTitle : "الاسم",
		budgetNameHintText : "الاسم الميزانية",
		amountTitle : "الكمية",
		revenueResourceTitle : "عائدات الموارد",
		amountHintText : "0",
		cycleTitle : "دورة",
		cycleHintText : "دورة",
		startDateTitle : "تاريخ البدء",
		endDateTitle : "تاريخ الانتهاء ",
		dateTitle : "التاريخ",

		noteTitle : "ملاحظة",
		noteHintText : "إضافة ملاحظة هنا",
		updateTitle : "تحديث",
		deleteTitle : "حذف",
		yourAvailableAmountTitle : "القيمة المتاحة لك",
		availableBalanceTitle : "الرصيد المتوفر",
		budgetLimitTitle : "حد الميزانية",
		yourBudgetTitle : "ميزانيتك",
		addBudgetTitle : "إضافة ميزانية",
		addExpenseTitle : "إضافة نفقة",
		addSourceTitle : "إضافة مصدر",
		totalText : "مجموع",
		AvailableText : "متاح",
		forTitle : "ل",
		//categoryTitle : "فئة",
		categoryTitle : "الفئة الرئيسية",
		createExpenseTitle : "إضافة نفقة",
		cancelTitle : "إلغاء",
		budgetTitle : " ميزتنية",
		actualTitle : "فعلي",

		manageExpenseBudgetTitle : "إدارة خطة الميزانية",
		manageExpensesTitle : "إدارة النفقات",
		budgetTitle : "ميزانية",
		expenseTitle : "نفقة",
		addMoreTitle : "إضافة المزيد",
		recentExpenseTitle : "المصروفات الحالية",
		//Revenue sources
		salary : "الراتب",
		dividend : "حصة",
		rent : "إيجار",
		familySupport : "دعم الأسرة",
		saving : "توفير",

		budgetAmountTitle : "مبلغ الميزانية",
		availableAmountTitle : "المبلغ المتاح",
		amountSpentAlreadyTitle : "المبلغ المنفق بالفعل",
		maximumBudgetAmountTitle : "أقصى مبلغ للميزانية",
		currentlyAllocatedBudget : "الميزانية المخصصة حاليا",

		myBudgetCreateSuccessMsg : "تم إنشاء ميزانيتك بنجاح.",
		myBudgetUpdateSuccessMsg : " تم تحديث ميزانيتك بنجاح",
		myBudgetDeleteSuccessMsg : "تم حذف الميزانية بنجاح",
		expenseCreateSuccessMsg : "تم إنشاء النفقات بنجاح",
		revenueSourceCannotBeLessThanExpenseMsg : "مصدر الدخل لا يمكن أن يكون أقل من المصروفات.",
		revenueSourceCannotBeLessThanBudgetAmountMsg : "كمية مصدر دخل لا يمكن أن يكون أقل من مبلغ الميزانية",
		budgetAmountCannotBeLessThanExpenseMsg : "مبلغ الميزانية لا يمكن أن يكون أقل من المصروفات",
		budgetAmountCannotBeGreaterThanRevenueSourcesAmountMsg : "مبلغ الميزانية لا يمكن أن يكون أكبر من الإيرادات",
		plzEnterAtleastOneExpenseMsg : "الرجاء إدخال واحد على الأقل من التفاصيل حساب",
		expenseAmountCannotBeGreaterThanAvailableBudgetAmountMsg : "مقدار نفقة لا يمكن أن يكون أكبر من مبلغ الميزانية المتاحة",
		revenueSources : "مصادر الإيراد",
		expenseCategories : "فئات الصرف",
		budgetAmountCannotBeLessThanExpenseCategoryMsg : "Budget amount cannot be less than already allocated expenseCategory amount",

		//Expense category
		expenseCategoryTitle : "تصنيف النفقة",
		foodDrink : "المأكولات و المشروبات",
		mobileExpense : "مصاريف الهاتف",
		clothes : "الملابس",
		carMaintenance : "صيانة السيارة",
		fuel : "الوقود",
		gym : "الجمنازيوم",
		shopping : "التسوق",
		medical : "طبي",
		movie : "أفلام",
		metroTravelExpense : "مصروفات المترو",
		party : "حفلة",
		parkingExpense : "مصروفات المواقف ",
		friends : "الأصدقاء",

		// Tax & Vat
		TaxAndVat : "شهادتا الموطن الضريبي والقيمة المضافة",
		newVApplication : "طلب إصدار شهادة القيمة المضافة",
		newTApplication : "طلب إصدار شهادة الموطن الضريبي",
		taskList : "متابعة الطلبات المقدمة",
		applicationList : "الطلبات السابقة",
		changePassword : "تغيير كلمة السر",
		profile : "الملف الشخصي",
		edit : "تعديل",
		password : "كلمة السر",

		address : "العنوان",
		mobileNoNormal : "رقم الهاتف المتحرك",
		telNo : "رقم الهاتف",
		faxNo : "رقم الفاكس",
		POBox : "صندوق البريد",
		save : "حفظ",
		new : "جديد",
		application : "طلب",
		title : "العنوان",
		tasks : "المهام",
		status : "الحالة",
		editApplication : "تعديل الطلب",
		viewApplication : "استعراض بيانات الطلب",
		taxApplication : "الموطن الضريبي",
		vatApplication : "القيمة المضافة ",
		applicationDetail : "تفاصيل الطلب",
		attachments : "المرفقات",
		attachMedia : "إرفاق وسائط",
		cameraNotAvail : "لاتتوفر كاميرا في الجهاز",
		useCamera : "استخدم الكاميرا",
		useDropbox : "Dropbox اختر من",
		//"اختر من دروببوإكس",
		selectFromGallery : "اختر من البوم الصور",
		enterUserName : "يرجى إدخال اسم المستخدم",
		enterTaxName : "من فضلك ادخل الاسم ",

		
		aboutTitle : "من نحن",
		visionMission : "الرؤية والرسالة والقيم",
		topManagement : "الإدارة العليا",
		strategicGoals : "الأهداف الاستراتيجية",
		achievements : "الإنجازات",
		minsitryplan : "الخطة الاستراتيجية للوزارة",
		ministryAchievements : "إنجازات الوزارة منذ عام 2008",
		//News
		newsMofTitle : "عناوين الأخبار",
		newsDetails : "تفاصيل الأخبار",
		searchHint : "بحث",
		no : "لا",
		personalDetails : "تفاصيل الشخصية",
		nationality : " الجنسية",
		dateofbirth : " تاريخ الميلاد",
		kids : " الأطفال",
		dateAppointment : "تاريخ التعيين",
		paySlip : "تفاصيل قسيم الدفع",
		payPeriod : "فترة الدفع",
		days : " أيام",
		grade : "الدرجة",
		latestUpgrade : "أحدث ترقية",
		basicSalary : "الراتب الأساسي",
		bankAccount : "الحساب",

		accountno : " رقم الحساب",
		//status:
		benefits : "فوائد",

		costLivingPremium : " تعلاوة المعيشة",
		carTransportPremium : "علاوة المواصلات",
		supplementalAllowance : "علاوة تكميلية",
		totalbenefit : "إجمالي المخصصات",
		deductions : "الخصومات",
		leaveAdvanceDeduction : " خصم غياب مسبق",
		totalDeduction : "إجمالي الخصم",
		netSalary : "صافي الراتب",

		budgetbyActivity2014 : " الميزانية  2014",
		selectSector : "حدد القطاع",
		total : "مجموع",
		chapter2 : " الفصل 2",
		chapter3 : " الفصل 3",
		strategicObjective : "الهدف الاستراتيجي",
		programs : "برامج",
		presentationStyle : "طريقة التقديم",
		barGraph : "شريط الرسم البياني",
		pieChart : "مخطط دائري",
		done : " انتهى",
		month1 : "شهر واحد",
		month2 : "شهرين",
		month3 : "3 شهور",
		or : "أو",
		call : "مكالمة",
		callTitle : "هل أنت متأكد؟",

		direction : "اتجاه",
		steps : "خطوات",
		from : "من",
		to : "إلى",
		totalDuration : "إجمالي المدة",
		totalLength : "الطول الكلي",

		loading : "تحميل",

		// mSupplier Module

		login : "دخول",
		iSupplier : "خدمات الموردين",

		purchaseOrder : "أوامر الشراء",
		invoices : "الفواتير",
		payments : "الدفعات",
		fmisSupports : "الدعم الفني",
		tenderBidsProcurements : "استعراض المناقصات والممارسات",
		search : "بحث",
		entity : "الجهة",
		orderDate : "تاريخ الطلب",
		viewInvoices : "استعراض الفواتير",
		invoiceDate : "تاريخ الفاتورة",
		due : "المبلغ المستحق",
		dueDate : "تاريخ الاستحقاق",
		paymentStatus : "حالة الدفعة",
		paymentDetails : "تفاصيل الدفعة",
		invOfPurOrder : "فواتير أمر الشراء رقم",
		payOfInvNo : "دفعات الفاتورة رقم",
		paymentDate : "تاريخ الدفع",
		method : "الوسيلة",
		bankAccount : "الحساب المصرفي",
		loginDescription : "يرجى تقديم المعلومات التالية",
		forgotPassword : "هل نسيت كلمة السر؟",
		lblForgotPassword : "نسيت كلمة السر",
		userName : "اسم المستخدم",
		password : "كلمة السر",
		//logout : "تسجيل الخروج",
		logout : "خروج",
		enterInvoiceNo : "أدخل رقم الفاتورة",
		enterOrderNo : "أدخل رقم أمر الشراء",
		enterValidNo : "يرجى إدخل الرقم بشكل صحيح",
		general : "عام",
		companyProfile : "ملف الشركة",
		supplierName : "اسم المورد",
		supplierNo : "رقم المورد",
		registrationDate : "تاريخ التسجيل",
		renewalDate : "تاريخ التجديد",
		expirationDate : "تاريخ انتهاء التسجيل",
		legal : "قانوني",
		genDirectorName : "اسم المدير العام",
		activity : "نوع النشاط",
		partners : "الشركاء",
		partnership : "شراكة",
		workplace : "مكان العمل",
		busClassification : "بيانات سجل الشركة",
		certificate : "شهادة",
		reference : "المرجع",
		expDate : "تاريخ الانتهاء",
		categoryName : "التصنيف",
		lastUpdateBy : "اخر تحديث من قبل",
		lastUpdateOn : 'اخر تحديث في ',
		enterLoginPassword : "يرجى إدخال قيم صحيحة للبريد الالكتروني وكلمة السر",
		//"يرجى إدخال قيم صحيحة لاسم المستخدم وكلمة السر",
		noRecordFound : "لاتتوفر معلومات",

		eventName : "الإصدار",
		title : "العنوان",
		openDate : "تاريخ الإصدار",
		closeDate : "تاريخ الإغلاق",
		price : "السعر",
		Number : "رقم",
		ticketNo : "رقم التذكرة",
		ticketDetails : "تفاصيل التذكرة",
		subCategory : "الفئة الفرعية",
		createTicket : "إنشاء تذكرة جديدة",
		selectDepartment : "اختر الدائرة",
		selectCategory : "اختر الفئة الرئيسية",
		selectSubCategory : "إختر الفئة الفرعية",
		all : "الجميع",
		closed : "مغلقة",
		inProgress : "قيد المعالجة",
		reopen : "إعادة فتح",
		contacts : "بيانات الاتصال",
		bankDetails : "تفاصيل المصرف",
		userAccount : "حساب المستخدم",
		isUserRemovable : "هل المستخدم قابل للحذف",
		accountNumber : "رقم الحساب",
		iban : "IBAN",
		currency : "العملة",
		bankName : "اسم البنك",
		createTicket : "إنشاء تذكرة",
		viewTicket : "استعراض التذاكر",
		selectFederalEntity : "حدد الجهة الاتحادية",
		others : "اخرى",
		SuppFederalEntity : "مورد للجهات الاتحادية",
		support : "الدعم الفني",

		noDetailsFound : "لا توجد تفاصيل",
		getInvoices : "جلب فواتير",
		getPayments : "جلب دفعات",
		imgTooBig : "حجم الصورة يتجاوز الحجم المسموح به",
		contactReqMsg : "تم إرسال الطلب بنجاح",
		contactErroMsg : "تعذر إرسال الطلب. يرجى إعادة المحاولة لاحقا",
		imageLimitMsg : "يمكنك اختيار 5 صور كحد أقصى",
		enterValidPhoneMsg : "يرجى إدخال رقم هاتف صحيح",
		statusSubTickets : "حالة التذاكر المستلمة",
		noTicketFound : "لم يعثر على التذكرة المطلوبة",
		createTicketMsg : "هل ترغب في إنشاء تذكرة جديدة؟",
		enterRevenueSourceTitleMsg : "اسم مصدر الإيرادات",
		enterRevenueSourceValueMsg : "مقدار مصدر الإيرادات",
		maximuAllowedResourcesCountReachMsg : "وصلت إلى الحد الأقصى من المصادر. لا يمكنك إضافة مصدر جديد",
		endDateCannotbeLess : "تاريخ الانتهاء لا يمكن أن يقل عن تاريخ البداية",
		userRegistration : "تسجيل المستخدم",
		newPassword : "كلمة المرور الجديدة",
		//"كلمة المرور الجديدة",
		enterNewPassword : "أدخل كلمة السر الجديدة",
		changePasswordSuccessMsg : "تم تغيير كلمة المرور بنجاح",
		//Reports
		fgFinalAccount : 'تقارير الحساب الختامي',
		budgetExecutionRevenue : "تنفيذ الميزانية العامة للاتحاد ",
		budgetExecutionExpense : "Budget Execution By Expenses",
		budgetExecutionByCofog : "تنفيذ الميزانية العامة للاتحاد على مستوى قطاعات وظائف الحكومة",
		expenseRevenueKPI : "Budget Average KPI",
		revenueAllocated : "الإيرادات المعتمدة",
		revenueExecuted : "الإيرادات المنفذة",
		expenditureAllocated : "المصروفات المعتمدة",
		expenditureExecuted : "المصروفات المنفذة",

		gfsReports : 'تقارير إحصاءات مالية الحكومة',
		gfsReportsByRevenueAndExpense : "GFS Reports by Revenue and Expense",
		statementsOfGovtOperationsAssetsAndLiabilities : "البيانات المالية المجمعة على مستوى الدولة – الأصول والخصوم",
		statementsOfGovtOperationsIndices : "Statements of Government Operations - Indices",
		outlaysReportsFunctionsByGovt : "Outlays Reports Funcitons By Government",
		revenueAvg : "Revenue Average KPI",
		expenditureAvg : "Expenditure Average KPI",

		//Open Financial Data
		lblFederalBudget : "الميزانية العامة للحكومة الاتحادية",
		gfsFederalUnion : "الميزانية العامة للحكومة الاتحادية",
		gfsRev_Exp : "البيانات المالية المجمعة على مستوى الدولة – الايرادات والمصروفات",
		gfsAsse_Lia : "البيانات المالية المجمعة على مستوى الدولة – الأصول والخصوم",
		gfsIndicies : "البيانات المجمعة على مستوى الدولة – المؤشرات التحليلية",
		gfsOutlays : "التصنيف الوظيفي لنفقات الحكومة على مستوى الدولة",
		description : "الوصف",
		total : "المجموع",
		code : "الرمز",
		revenue : "الإيرادات",
		expense : "المصروفات",
		value : "القيمة",
		budget : "الميزانية",

		// Dahsboard
		openFinancialData : "البيانات المالية المفتوحة",
		gccStatisticalBook : "التقرير الإحصائي للسوق الخليجية",
		customerInteraction : "آراء المتعاملين",
		mChatting : "المحادثة الذكية",
		locationFedEntity : "دليل الجهات الاتحادية",

		// open financial data
		budgetExecutionGroupByRevenue : "تنفيذ الميزانية العامة للاتحاد - الإيرادات ",
		budgetExecutionGroupByExpenditure : "تنفيذ الميزانية العامة للاتحاد - المصروفات",
		budgetExecutionByRevenue : "تنفيذ الميزانية العامة للاتحاد - الإيرادات",
		budgetExecutionByExpenditure : "تنفيذ الميزانية العامة للاتحاد - المصروفات",
		budgetExecutionByCofog : "تنفيذ الميزانية العامة للاتحاد على مستوى قطاعات وظائف الحكومة",
		revenueKPI : "مؤشر دقة التخطيط المالي للايرادات العامة",
		expenditureKPI : "مؤشر دقة التخطيط المالي للمصروفات العامة",
		revenueExpenditureKPI : "Revenue/Expenditure KPI",
		assetsLiabilities : "الأصول والخصوم",
		revenueExpenses : "الايرادات والمصروفات",
		values : "القيمة",
		indicies : "المؤشرات",
		cofogs : "قطاعات الوظائف",
		years : "السنة",
		mof : "MOF",

		//Location Federal
		locateFederal : 'دليل الجهات الاتحادية',
		direction : "اتجاه",
		steps : "خطوات",
		from : "من",
		to : "إلى",
		totalDuration : "إجمالي المدة",
		totalLength : "الطول الكلي",

		//Contact MOF
		detail : "Detail",
		map : "خارطة الموقع",
		abuDhabi : "أبوظبي",
		dubai : "دبي",
		phone : "رقم الهاتف",
		fax : "رقم الفاكس",
		website : "الموقع الالكتروني",
		sendMail : "بريد الكتروني",
		mailAccountMsg : "البريد الالكتروني غير متاح. الرجاء مراجعة اعدادات البريد الالكتروني",

		dashBoard : "لوحة القيادة",
		addnote : "إضافة ملاحظة هنا",
		confirmPassword : "تأكيد كلمة السر",
		//"كلمة السر للتأكيد",
		confirmPassMsg : "يجب أن تتطابق كلمة السر وتأكيد كلمة السر",
		confirmNewPassMsg : "يجب أن تتطابق كلمة المرور الجديدة وتأكيد كلمة السر",
		enterValidMobile : "Enter valid mobile number",
		enterValidPhone : "Enter valid phone number",
		enterValidFax : "Enter valid fax number",
		codeTitle : "الرمز",
		noCategoryAvailable : "ليس ثمة فئات صرف",
		enterValidPOBox : "Enter valid P.O. Box",
		deleteBudgetMsg : "هل أنت متأكد من رغبتك في حذف هذه الميزانية؟",
		expenseDateMsg : "تاريخ الصرف يجب أن يقع ضمن مدة سريان الميزانية:",
		budgetstartDateMsg : "تاريخ البداية لا يمكن أن يتجاوز تاريخ الانتهاء",
		budgetEndDateMsg : "تاريخ الانتهاء لا يمكن أن يقل عن تاريخ البداية ",
		deleteBudget : "حذف ميزانية",
		NoExpenseCategory : "لاتوجد فئة صرف لهذه الميزانية",
		PasswordValidMsg : "يجب أن لاتقل كلمة السر عن 8 رموز، وأن تحتوي على الإقل على رقم وحرف كبير ورمز خاص",
		spentAmount : "المقدار المنفق : ",
		viewMore : "المزيد...",

		spent : "الأصـول",
		expenses : "المصـروفات",
		assets : "الأصـول",

		allocatedRevenue : "الإيرادات المعتمدة",
		executedRevenue : "الإيرادات المنفذة",
		allocatedExpenditure : "المصروفات المعتمدة",
		executedExpenditure : "المصروفات المنفذة",

		//takamul new
		selectRequestType : "حدد نوع الموضوع",
		details : "تفاصيل",
		createRequest : "Create Request",
		enterYourDetails : "أدخل التفاصيل",
		theRespondent : "The Respondent",
		theRespondentLoc : "The Respondent Location",
		requestList : "قائمة الطلبات المرسلة",
		createNewRequest : "طلب جديد",
		newUserRegister : "New User Registration",
		selectUserType : "Select User Type",
		selectCountry : "اختر الدولة",
		enterUserName : "Enter User Name",
		enterEmailHint : 'Enter Email',
		enterMobileNo : "Enter Mobile No.",
		enterPasswordHint : "Enter Password",
		enterDetails : "Enter Details",
		userFeedback : "رأي المستخدم",
		enterComments : "أدخل ملاحظات",
		contactGov : "لاقتراحاتكم وملاحظاتكم، يرجى استخدام بوابة الاقتراحات والملاحظات لحكومة دولة الامارات",
		selectAttachmentType : "اختر المرفقات",
		viewRequest : "View Request",
		reply : "Reply",
		replyRequest : "Reply Request",
		customerInquiry : "استفسارات المتعاملين",
		firstSelectCategory : "يرجى اختيار الفئة أولا",

		// Msupplier
		supplierRegistration : "تسجيل الموردين",
		supplierEditRegistration : "Edit Profile",
		step1 : "خطوة 1",
		step2 : "خطوة 2",
		step3 : "خطوة 3",
		step4 : "خطوة 4",
		basicInfo : "معلومات أساسية",
		companyDetails : "تفاصيل الشركة",
		companyNameAr : "اسم الشركة (عربي)",
		companyRegistrationNo : "رقم السجل التجاري",
		companyNameEn : "اسم الشركة (انجليزي)",
		contactInfo : "بيانات الاتصال",
		contactName : "اسم ممثل الشركة",
		mobileNumberColon : "رفم الموبايل",
		telephoneColon : "رقم الهاتف",
		basicClassification : "بيانات الترخيص",
		classification : "الرخص",
		classicCertificate1 : "رقم رخصة غرفة التجارة",
		classicExpiryDate1 : "تاريخ انتهاء صلاحية رخصة غرفة التجارة",
		classicCertificate2 : "رقم السجل التجاري",
		classicExpiryDate2 : "تاريخ انتهاء صلاحية السجل التجاري",
		classicCertificate3 : "رقم الرخصة التجارية",
		classicExpiryDate3 : "تاريخ انتهاء صلاحية الرخصة التجارية",
		addressDetails : "سجل العناوين",
		addressName : "اسم العنوان",
		addressLine1 : "سطر العنوان 1",
		addressLine2 : "سطر العنوان 2",
		country : "الدولة",
		emirate : "الإمارة",
		city : "المدينة",
		poBox : "صندوق البريد",
		registrationFees : "دفع رسوم تجديد التسجيل",
		businessClassification : "تحديث الرخص",
		uploadNewDoc : "تحميل وثيقة جديدة",
		renewal : "تجديد التسجيل في سجل الموردين",

		mParticipation : "المشاركة الذكية",
		composeComment : "ملاحظات",
		compose : "تحرير",
		personalDetails : "التفاصيل الشخصية",
		firstName : "الاسم الأول",
		mobileNo : "رقم الموبايل",
		addMoreDetails : "تفاصيل إضافية",
		userSatisfaction : "رضا المستخدم عن الخدمة",
		userSatisfactionSuggestion : "هل تود المشاركة في استبيان قصير لتقويم الخدمة؟",
		thankYouUserSatisfaction : "شكرا لمساهمتك",
		feedback : "نعم",
		skip : "لا",
		emailAddress : "البريد الالكتروني",
		mobileNumber : "رقم الموبايل",
		addNewUser : "إضافة مستخدم جديد",
		drafts : "مسودات",
		createdBy : "تم إنشاؤها بواسطة",
		lastModified : "آخر تعديل فى",
		thankYouAddUser : "تم إرسال طلب إضافة مستخدم جديد.",
		lastName : "الاسم الأخير:",
		emailAddressColon : "البريد الالكتروني:",
		gender : "الجنس:",
		ageGroup : "الفئة العمرية:",
		comment : "ملاحظات:",
		_selectNationality : "--- اختر الجنسية ---",
		_selectGender : "--- اختر الجنس ---",
		_selectAgeGroup : "--- اختر الفئة العمرية ---",
		commentAdded : "تم إضافة ملاحظاتك",
		addComment : "إضافة ملاحظة",
		by : "بواسطة",
		ago : "منذ",
		_selectEmirate : "-- اختر الإمارة --",
		bankDetails : "تفاصيل البنك",
		country : "الدولة",
		branchNo : "رقم الفرع",
		bankNo : "رقم البنك",
		bankName : "اسم البنك",
		branchName : "اسم الفرع",
		accountName : "اسم الحساب",
		currency : "العملة",
		ibanNo : "رقم IBAN",
		_selectCountry : "-- اختر الدولة --",
		_selectBankName : "-- اختر اسم البنك --",
		_selectBranchName : "-- اختر اسم الفرع --",
		_selectCurrency : "-- اختر العملة --",
		contactDetails : "تفاصيل ممثلي الشركة",
		contactTitle : "لقب الممثل",
		_firstName : "الاسم الأول",
		middleName : "الاسم الأوسط",
		jobTile : "الوظيفة",
		__selectContactTitle : "-- اختر لقب الممثل --",
		addressDesc : "بيانات العنوان",
		bankAccNo : "رقم الحساب المصرفي",
		bankName_branchName : "اسم البنك/الفرع",
		additionalInfo : "معلومات إضافية",
		companyAddInfo : "تفاصيل إضافية عن الشركة",
		legalEntity : "الكيان القانوني",
		__selectLegalEntity : "-- اختر كيانا --",
		generalDirectorNationality : "جنسية المدير العام",
		__selectGeneralDirectorNationality : "-- اختر الجنسية --",
		generalDirectorName : "اسم المدير العام",
		attachmentDetails : "المرفقات",
		certificateNumber : "رقم الشهادة",
		partnersDetails : "تفاصيل الشركاء",
		ownerName : "اسم الشريك",
		nationality : "الجنسية",
		partnership : "نسبة الشراكة",
		citizenPartner : "جهة عمل الشريك المواطن",
		_nationality : "-- اختر الجنسية --",
		attachmentsDetails : "تفاصيل المرفقات",
		text : "نص",
		_selectCategory : "-- اختر الفئة --",
		enterCompanyEn : "يرجى إدخال اسم الشركة بالانجليزية",
		enterCompanyAr : "يرجى إدخال اسم الشركة بالعربية",
		enterCompanyRegNo : "يرجى إدخال رقم السجل التجاري للشركة",
		enterContactName : "يرجى إدخال اسم ممثل الشركة",
		enterTelPhNo : "يرجى إدخال رقم الهاتف",
		thankYouConfirmPayment : "اكتملت عملية دفع الرسوم بنجاح",
		paymentFailure : "فشلت عملية دفع الرسوم",
		invalidRegisterNo : "رقم السجل التجاري يتكون من أرقام فقط",
		invalidTelPhoneNo : "رقم الهاتف يتكون من أرقام فقط",
		mSuppFirstName : "يرجى إدخال الاسم الأول",
		enterAddressName : "يرجى إدخال اسم العنوان",
		enterAddressLine1 : "يرجى إدخال سطر العنوان 1",
		enterAddressLine2 : "يرجى إدخال سطر العنوان 2",
		selectEmirate : "اختر الإمارة",
		enterCity : "أدخل المدينة",
		mSupEnterPOBox : "أدخل صندوق البريد",
		mSupInvalidPOBox : "يرجى إدخال قيمة صحيحة لصندوق البريد وإدخال الأرقام باللغة الانجليزية",
		enterBankAccountNo : "أدخل رقم الحساب البنكي",
		enterAccountName : "أدخل اسم الحساب",
		selectBranchName : "أدخل اسم الفرع",
		selectBankName : "اختر اسم البنك",
		selectCountryName : "اختر الدولة",

		selectCurrency : "اختر العملة",
		enterIBANNo : "أدخل رقم IBAN",
		enterMiddleName : "أدخل الاسم الأوسط",
		enterJobTitle : "أدخل المسمى الوظيفي",
		enterGeneralDirectorName : "أدخل اسم المدير العام",
		selectLegalEntity : "اختر الكيان القانوني",
		selectGeneralDirectorNationality : "اخنر جنسية المدير العام",
		selectActivity : "اختر نشاطا واحدا على الأقل",
		enterPartnerDetails : "أدخل تفاصيل الشركاء",
		enterOwnerName : "أدخل اسم الشريك",
		enterPartnership : "أدخل نسبة الشراكة",
		invalidPartnership : "نسبة الشراكة يجب أن تكون رقما فقط",
		enterCitizenPartner : "أدخل جهة عمل الشريك المواطن",
		mSupSelectNationality : "اختر الجنسية",
		enterTitle : "أدخل العنوان",
		selectAttachment : "اختر المرفقات", //
		addressMandatory : "لابد من إدخال عنوان واحد على الأقل",
		bankMandatory : "لابد من إدخال حساب بنكي واحد على الأقل",
		activityMandatory : "لابد من إدخال نشاط واحد على الأقل",
		partnerMandatory : "ينبغي أن تكون نسبة الشراكة تساوي 100.",
		cannotAddNewPartner : "وصلت نسبة الشراكة إلى 100%. لذا، لايمكنك إضافة المزيد من الشركاء",
		partnerShipMaxValueCanEnter : "أقصى قيمة يمكن إدخالها هي:",
		enterConfirmPasswordHint : "أدخل تأكيد كلمة السر",
		//"أدخل كلمة السر للتأكيد",
		enterAddressHint : "أدخل العنوان",
		enterName : "يرجى إدخال اسم المستخدم",

		enterPassword : "يرجى إدخال كلمة السر",
		enterNewPassword : "يرجى إدخال كلمة المرور الجديدة",
		enterConfirmPassword : "يرجى إدخال كلمة السر مرة أخرى",
		enterEmail : "يرجى إدخال البريد الالكتروني",
		invalidUserType : "يرجى تحديد نوع المستخدم",
		enterAnswer : "يرجى إدخال الإجابة",
		next : "التالي",
		logOutMessage : "هل أنت متأكد أنك تريد الخروج؟",
		enterEmailAddress : "أدخل البريد الالكتروني",
		selectMaximiumFive : "يمكنك إرفاق 3 وثائق كحد أقصى",
		exitRegistration : "هل أنت متأكد من رغبتك في الخروج من عملية التسجيل؟",
		fillAddressDetails : "يرجى تعبئة تفاصيل العنوان",
		fillBankDetails : "يرجى تعبئة التفاصيل البنكية",
		fillContactDetails : "يرجى تعبئة تفاصيل ممثلي الشركة",
		enterCerNo1 : "يرجى إدخال رقم رخصة غرفة التجارة",
		enterExp1 : "يرجى إدخال تاريخ انتهاء صلاحية رخصة غرفة التجارة",
		enterCerNo2 : "يرجى إدخال رقم السجل التجاري",
		enterExp2 : "يرجى إدخال تاريخ انتهاء صلاحية السجل التجاري",
		enterCerNo3 : "يرجى إدخال رقم الرخصة التجارية",
		enterExp3 : "يرجى إدخال تاريخ انتهاء صلاحية الرخصة التجارية",

		deleteAttachment : "هل أنت متأكد من رغبتك في حذف هذا المرفق؟",
		dataSuccess : "تم تحديث البيانات بنجاح",
		incorrectAnswer : "جواب خاطئ",
		cameraNotAccess : "لم يتمكن هذا التطبيق من الوصول للكاميرا",
		camera : "كاميرا",
		oldPassword : "كلمة السر القديمة",
		enterOldPassword : "أدخل كلمة السر القديمة",
		noDataAvailableAtTheMoment : "لاتتوفر بيانات حاليا",
		answer : "الجواب",
		transactionId : "رمز الحركة المالية",
		transactionAmount : "قيمة الحركة المالية",
		confirmationId : "رمز التأكيد",
		confirmationDate : "تاريخ التأكيد",

		// vat and tax start

		selectCertificateDMethod : "يرجى اختيار طريقة تسلم الشهادة",
		enterCompanyName : "يرجى إدخال اسم الشركة/الجهة الحكومية",
		selectFinancialYear : "الرجاء تحديد السنة المالية",
		enterChamberOfCom : "يرجى إدخال عضوية غرفة التجارة",
		enterTradeLicenseNo : "يرجى إدخال رقم الرخصة التجارية",
		plsSelectEmirate : "يرجى اختيار الإمارة",
		enterAddress : "يرجى إدخال العنوان",
		enterMobile : "يرجى إدخال رقم الهاتف المتحرك",
		invalidMobileNo : "يرجى إدخال رقم هاتف متحرك صحيح",
		invalidFaxNo : "يرجى إدخال رقم فاكس صحيح",
		invalidPhoneNo : "يرجى إدخال رقم هاتف صحيح",
		enterPOBox : "يرجى إدخال رقم صندوق البريد",
		invalidPOBox : "يرجى إدخال رقم صندوق بريد صحيح",
		enterEmail : "يرجى إدخال البريد الالكتروني",
		invalidEmail : "يرجى إدخال بريد الكتروني صحيح",
		selectCountryIssued : "يرجى اختيار الدولة الموجه إليها الشهادة",
		selectPlaceOfIssue : "يرجى اختيار مكان إصدار الشهادة",
		selectLanguage : "يرجى اختيار لغة الشهادة",
		enterNatureOfBusiness : "يرجى إدخال طبيعة العمل",
		attachTradeLicense : "يرجى إرفاق رخصة تجارية سارية المفعول",
		attachSignedLetterCor : "يرجى إرفاق رسالة موقعة من الشركة",

		attachPassportCopy : "يرجى إرفاق صورة عن جواز السفر",
		attachVisaCopy : "يرجى إرفاق نسخة من التأشيرة",
		attachAuditCopy : "يرجى إرفاق نسخة من الحسابات المالية مدققة",
		attachLeaseCopy : "يرجى إرفاق صورة عن عقد الإيجار",
		enterPassportNumber : "يرجى إدخال رقم جواز السفر",
		selectNationality : "يرجى اختيار الجنسية",
		enterVisaNumber : "يرجى إدخال رقم الاقامة",
		enterNationalId : "Please enter the national id",
		//"يرجى إدخال رقم التأشيرة",
		enterWorkFor : "يرجى إدخال جهة العمل",
		attachResidencyCopy : "يرجى إرفاق صورة عن الإقامة",
		attachSignedLetterCustomer : "يرجى إرفاق رسالة موقعة من العميل",
		attachEmployerLetter : "يرجى إرفاق خطاب من جهة العمل",
		attachBankStatement : "يرجى إرفاق كشف حساب لمدة 6 أشهر",
		attachSalaryCertificate : "يرجى إرفاق شهادة راتب صالحة",
		attachEmployementContract : "يرجى إرفاق نسخة من عقد العمل مصدق من وزارة العمل",
		vatTaxSuccess : "تم تسجيل طلبك بنجاح",
		draft : "مسودة",
		approval : "موافقة",

		userType : "نوع المستخدم",
		individual : "فرد",
		corporate : "شركة",
		government : "للحكومة",
		
		certificateDelivery : "طريقة تسلم الشهادة",
		financialYear : "تاريخ بداية الصلاحية",
		financialYearNote : "الشهادة صالحة لمدة عام من هذا التاريخ",
		companyName : "اسم الشركة/الجهة الحكومية",
		chamberOfCommerce : "عضوية غرفة التجارة",
		tradeLicenseNo : "رقم الرخصة التجارية",
		emirate : "الإمارة",
		seconadryMobile : "رقم شخص بديل",
		countryIssuedFor : "الدولة الموجه إليها",
		placeIssuingCertificate : "مكان إصدار الشهادة",
		certificateLanguage : "لغة الشهادة",
		natureOfBusiness : "طبيعة العمل",
		validTradeLicense : "رخصة تجارية سارية المفعول",
		signedLetter : "رسالة موقعة من الشركة",
		passportCopyOwners : "صورة عن جواز السفر لمالكي الشركة",
		visaCopyOwners : "صورة الإقامة لملاك الشركة",
		//"نسخة من التأشيرة لمالكي الشركة",
		copyAuditFinancialAccounts : "نسخة من الحسابات المالية مدققة",
		leaseCopy : "صورة عن عقد الإيجار",

		certificateType : "نوع الشهادة",
		certificateDeliveryMethod : "طريقة تسلم الشهادة",
		passportNo : "رقم جواز السفر",
		visNo : "رقم الإقامة",
		nationalId : "رقم الهوية",
		//"رقم التأشيرة",
		workFor : "جهة العمل",
		passportCopy : "نسخة جواز السفر",
		validResidenceCopy : "نسخة من الإقامة",
		letterSignedCustomer : "رسالة موقعة من العميل",
		letterFromEmployer : "خطاب من جهة العمل",
		certifiedBankAccount : "كشف حساب لمدة 6 أشهر",
		validSalaryCertiFicate : "شهادة راتب صالحة",
		employementContract : "نسخة من عقد العمل مصدق من وزارة العمل",

		registerTitle : "تسجيل",
		enterHintText : "أدخل ",

		instruction1 : "تحديد مصادر مختلفة من الإيرادات الخاصة بك، والتي سوف تحدد الحد الميزانية الخاصة بك.",
		instruction2 : "تسمية الميزانية الخاصة بك تقرر دورة وتعيين تواريخ البدء والانتهاء به.",
		instruction3 : "إضافة المصروفات من قائمة المصروفات المتاحة والتي ستشكل 'الميزانية' جزء من كل حساب.",
		instruction4 : "في وقت لاحق عند تكبد النفقات، يمكنك إدخال قيمة 'الفعلية' المستخدمة.",
		instruction5 : "في أي وقت، أنت حر في تعديل عناصر الميزانية.",

		contactContent : "This is Photoshop,s version of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet",
		phoneNumber : "رقم الهاتف",
		send : "أرسل",

		userCreatedSuccessMsg : "تم تسجيل المستخدم بنجاح",
		//userUpdatedSuccessMsg : "تم تحديث المستخدم بنجاح",
		userUpdatedSuccessMsg : "تم تحديث الملف الشخصي للمستخدم بنجاح",
		enterValidCompanyAr : "يرجى إدخال اسم الشركة باللغة االعربية",
		partnerShipGreater : 'نسبة الشراكة يجب أن لاتتجاوز 100',

		createNewAccount : "إنشاء حساب جديد",
		registration : "الدخول الى الخدمة",
		retry : "حاول ثانية",

		// Today :

		editRegistration : "تعديل",
		newResumeRegistration : "التسجيل/متابعة التسجيل في سجل الموردين",

		
		invalidName : "يرجى ادخال الأسم الصحيح",
		invalidCompanyName : "يرجى ادخال اسم الشركه الصحيح",
		invalidChamberOfCom : "يرجى ادخال عضوية الغرفة التجارية الصحيحة",
		invalidAnswer : "يرجى اختيار سؤال واحد على الاقل",
		notAccessRenewal : "التسجيل الخاص بك سينتهي بعد أكثر من شهر هل انت متأكد من الرغبة في التجديد",
		// invalidTelNo : "يرجى ادخال رقم التليفون الصحيح",
		// invalidPhNo : "رقم التليفون يجب ان يكون رقم”,جيل طلبك بنجاح”,

		//
		invalidTelNo : "يرجى إدخال رقم هاتف صحيح",
		enterPhoneNumber : "الرجاء إدخال رقم الهاتف",
		pay : "دفع الرسوم",
		invalidPhNo : "رقم الهاتف يتكون من أرقام فقط",
		securityQuestion : "أسئلة حماية الدخول",
		invalidSecurityQuestion : "يرجى اختيار 3 أسئلة على الأقل",
		select : "اختر ",
		serviceDescription : "وصف الخدمة",
		serviceProcessing : "خطوات تنفـيذ الخدمة",
		apply : "تقديم الطلب",
		enterSubject : "يرجى إدخال الموضوع",
		plsEnterComments : "يرجى إدخال ملاحظاتك",
		plsSelectRequestType : "يرجى اختيار طبيعة الموضوع",
		sQuestionSelected : "تم الإختيار",
		notAccessDropbox : "Dropbox لايمكنك استخدام ",
		attachmentNote : "Dropbox يرجى اختيار المرفق من الكاميرا/معرض الصور أو من خلال ",
		renewFees : "تجديد",
		invalidCompose : "Please provide comments to submit",
		selectFeedbacktype : "اختيار طبيعة الموضوع",
		englishNumberMandatory : "يرجى إدخال كافة الأرقام باللغة الانجليزية",
		stepsMandatory1 : "يرجى حفظ أية تعديلات تم إجراؤها",
		stepsMandatory2 : "قبل مغادرة الصفحة",
		
		endDate : "المشاركة متاحة حتى تاريخ: ",
		mSupplierReminderMsg : "إن البيانات المطلوبة عبر المراحل التالية على قدر كبير من الأهمية لتسجيلك. لذا، يرجى التأكد من دقتها، وبالأخص عناوين البريد الالكتروني. مع الشكر",
		mSupplierReminderTitle : "تذكـير",
		
		feesPayment : "دفع الرسـوم",
		paymentMsg : "سـيتم تحويلك الآن إلى منظومة الدرهم الالكتروني لدفع الرسـوم المستحقة",
		
		deletePartner : "هل أنت متأكد من رغبتك في حذف هذا الشريك؟",
		deleteActivity : "هل أنت متأكد من رغبتك في حذف هذا النشاط؟",
		add : "إضافة",
		
		proceed : "متابعة",
		languageInstruction : "يرجى اختيار اللغة التي سيتم إصدار الشهادة بها، وذلك من خلال اللغات المتاحة والمدرجة أدناه:",
		
		officialLetter :"رسالة رسمية موجهة للوزارة",
		establishmentDecree : "مرسوم تأسيس الجهة الاتحادية",
		attachOfficialLetter : "يرجى إرفاق رسالة رسمية موجهة للوزارة",
		attachEstablishment : "يرجى إرفاق مرسوم تأسيس الجهة الاتحادية",
	};
	return arabic;
};

