exports.language = function() {
	var english = {

		english : "English",
		arabic : "عربي",
		
		turnOnGPS : "Please turn on GPS",
		loading : "Loading...",
		updating : "Updating...",
		cancel : "Cancel",
		call : "Phone Call",
		callConformAlert : 'Are you sure you want to make a call to',
		noCallAlert : 'Phone call service not available',
		ok : "OK",
		serviceError : 'The service is currently unavailable. Please try again later.',
		doneTitle : "Done",
		// error : 'Error',
		error : '',
		language : "Change Language",
		noInternet : "No internet connection",
		// networkError : "Network Error",
		networkError : "",
		appTitle : "G2C",
		exitConfirm : "Are you sure you want to exit the application ?",
		yes : "Yes",
		no : "No",
		invalidRoute : "Routes are not available",

		//Fb & Twitter msgs
		shareFBSuccess : "Shared on facebook Successfully",
		shareTwitterSuccess : "Tweeted on twitter succesfully",
		shareFBFail : "Unable to share on facebook. Please try again later",
		shareTwitterFail : "Unable to share on twitter. Please try again later",
		getTweetsFail : "Unable to fatch tweets. Please try again later",
		duplicateMessage : "Duplicate message",
		facebookSuccessMessage : "Posted successfully",
		refNoTitle : "Reference Number",
		closeTitle : "Close",
		maximumImagesCountMsg : "Maximum allowed images count reached.Please delete some images in order to upload new image.",
		noAvailabliltyMsg : "Sorry, Not available ",

		//Form captions
		nameTitle : "Name",
		emailTitle : "Email",
		emailOrPhoneTitle : "Email or Phone",
		typeTitle : "Type",
		selectTypeTitle : "Select type",
		selectSubTypeTitle : "select sub type",
		subjectTitle : "Subject",
		descriptionTitle : "Description",
		locationTitle : "Location",
		textBoxHintText : "type",
		textBoxHintText_Message : "Enter Description",
		uploadImagesTitle : "Upload Images",
		saveTitle : "Save",
		submitTitle : "Submit",
		cancelTitle : "Cancel",
		resetTitle : "Reset",
		complaintSuccessMsg : "Complaint submitted successfully",
		helpdeskSuggestionSuccessMsg : "Your suggestion submitted successfully",
		helpDeskTitle : "Helpdesk",
		suggestionTitle : "Suggestion",

		//forms
		invalidEmailMsg : "Invalid Email",
		enterValidEmailMsg : "Enter valid Email ID",
		enterValidPhoneMsg : "Enter valid  phone number",
		plzEnterMissingFieldsMsg : "Please fill the followings :",
		noInformationAvailableMsg : "No information available",

		//Camera module
		chooseImageSourceTitle : 'Choose an image source...',
		cameraTitle : 'Camera',
		photoGalleryTitle : 'Photo Gallery',
		noCameraMsg : 'Device does not have camera',
		unexpectedErrorMsg : 'Unexpected error:',

		//hint text for complaints and Help
		enterNameHint : 'Enter Name',
		enterEmailPhoneHint : 'Enter Email or Phone',
		enterSubjectHint : 'Enter Subject',
		enterDescriptionHint : 'Enter Description',

		register : "Register",
		name : "Name",
		federalEntity : "Federal Entity",
		department : "Department/Section",
		email : "Email",
		emloyeeId : "Employee ID",
		nationalIdCard : "National ID Card",
		cancel : "Cancel",
		okLower : "Ok",

		taxVatTitle : "TAX Certificates",
		takamulTitle : "Takamul",
		myBudgetTitle : "My Budget",
		suppliersTitle : "Suppliers",
		reportsTitle : "Reports",
		notificationsTitle : "Notifications",
		aboutMOFTitle : "About MoF",
		contactMOFTitle : "Contact MoF",
		myBudgetReportTitle : "My Budget Report",
		newsTitle : "News",
		settingsTitle : "Settings",

		//Budget
		budgetIndtroductionMsg : "A light weight Application to help you create and manage your personal Budget.\nWhether you are a Professional Accountant,a Housewife or a Young School Student,you can easily set and track as many budgets as you like.",
		instructionsTitle : "Instructions",
		newBudgetTitle : "New Budget",
		existingBudget : "Existing Budget",
		noBudgetMsg : "No Budget \n add one with the + button",
		createBudgetTitle : "Create Budget",
		editBudgetTitle : "Edit Budget",
		nameTitle : "Name",
		budgetNameHintText : "Budget Name",
		amountTitle : "Amount",
		revenueResourceTitle : "Revenue Resource",
		amountHintText : "0",
		cycleTitle : "Cycle",
		cycleHintText : "Month(s)",
		startDateTitle : "Start Date",
		endDateTitle : "End Date",
		dateTitle : "Date",

		noteTitle : "Note",
		noteHintText : "Add note here",
		doneTitle : "Done",
		updateTitle : "Update",
		deleteTitle : "Delete",
		yourAvailableAmountTitle : "Your Available Amount",
		availableBalanceTitle : "Available Balance",
		budgetLimitTitle : "Budget Limit",

		yourBudgetTitle : "Your Budget",
		addBudgetTitle : "Add Budget",
		addExpenseTitle : "Add Actual Expense",
		addSourceTitle : "Add Source",
		totalText : "Total",
		AvailableText : "Available",
		forTitle : "For",
		categoryTitle : "Category",
		createExpenseTitle : "Create Actual Expense",
		cancelTitle : "Cancel",
		budgetTitle : " Budget",
		actualTitle : "Actual",

		manageExpenseBudgetTitle : "Manage Budget Expenses",
		manageExpensesTitle : "Manage Actual Expenses",
		budgetTitle : "Budget",
		expenseTitle : "Expense",
		addMoreTitle : "Add More",
		recentExpenseTitle : "Recent Expenses",
		//Revenue sources
		salary : "Salary",
		dividend : "Dividend",
		rent : "Rent",
		familySupport : "Family Support",
		saving : "Saving",

		budgetAmountTitle : "Budget Amount",
		availableAmountTitle : "Available Amount",
		amountSpentAlreadyTitle : "Already Spent Amount",
		maximumBudgetAmountTitle : "Maximum Budget Amount",
		currentlyAllocatedBudget : "Currently Allocated Budget",

		myBudgetCreateSuccessMsg : "Your budget has been created successfully.",
		myBudgetUpdateSuccessMsg : "Your budget has been updated successfully.",
		myBudgetDeleteSuccessMsg : "Budget has been deleted successfully",
		expenseCreateSuccessMsg : "Expenses has been created successfully",
		revenueSourceCannotBeLessThanExpenseMsg : "Revenue source amount cannot be less than already spent expenses amount",
		revenueSourceCannotBeLessThanBudgetAmountMsg : "Revenue source amount cannot be less than budget amount",
		budgetAmountCannotBeLessThanExpenseMsg : "Budget amount cannot be less than already spent expenses amount",
		budgetAmountCannotBeGreaterThanRevenueSourcesAmountMsg : "Budget amount cannot be greater than revenue sources amount",
		plzEnterAtleastOneExpenseMsg : "Please enter atleast one expense details",
		expenseAmountCannotBeGreaterThanAvailableBudgetAmountMsg : "Expense amount cannot be greater than available budget amount",
		revenueSources : "Revenue Sources",
		expenseCategories : "Expense Categories",
		budgetAmountCannotBeLessThanExpenseCategoryMsg : "Budget amount cannot be less than already allocated expenseCategory amount",

		//Expense category
		expenseCategoryTitle : "Expense Category",
		foodDrink : "Food & Drink",
		mobileExpense : "Mobile Expense",
		clothes : "Clothes",
		carMaintenance : "Car Maintenance",
		fuel : "Fuel",
		gym : "Gym",
		shopping : "Shopping",
		medical : "Medical",
		movie : "Movie",
		metroTravelExpense : "Metro Travel Expense",
		party : "Party",
		parkingExpense : "Parking Expense",
		friends : "Friends",

		// Tax & Vat
		TaxAndVat : "TAX & VAT",
		newVApplication : "Issue a New VAT Certificate",
		newTApplication : "Issue a New TAX Domicile Certificate",
		taskList : "My Tasks",
		applicationList : "My Applications",
		changePassword : "Change Password",
		profile : "Profile",
		edit : "Edit",
		password : "Password",
		address : "Address",
		mobileNoNormal : "Mobile No",
		telNo : "Telephone No",
		faxNo : "Fax No",
		POBox : "P.O Box",
		save : "Save",
		new : "New",
		application : "Application",
		title : "Title",
		tasks : "Tasks",
		status : "Status",
		editApplication : "Edit Application",
		viewApplication : "View Application",
		taxApplication : "TAX Application",
		vatApplication : "VAT Application",
		applicationDetail : "Application Details",
		attachments : "Attachments",
		attachMedia : "Attach media",
		cameraNotAvail : "Camera not available",
		useCamera : "Use camera",
		useDropbox : "Select from Dropbox",
		selectFromGallery : "Select from gallery",
		enterUserName : "Please enter the user name",
		enterTaxName : "Please enter the name",
		
		// manu  Aboutus
		aboutTitle : "About Us",
		visionMission : "Vision & Mission",
		topManagement : "Top Management",
		strategicGoals : "Strategic Goals",
		achievements : "Achievements",
		minsitryplan : "Ministry's Strategic Plan",
		ministryAchievements : "Ministry Achievements from 2008",
		//News
		newsMofTitle : "News Headlines",
		newsDetails : "News Details",
		searchHint : "Search",

		// ISupplier Module
		iSupplier : "mSupplier Services",
		login : "Login",
		profile : "Profile",
		purchaseOrder : "Purchase Order",
		invoices : "Invoices",
		payments : "Payments",
		fmisSupports : "FMIS Support",
		tenderBidsProcurements : "View Tender, Bids & Procurements",
		search : "Search",
		entity : "Entity",
		orderDate : "Order Date",
		viewInvoices : "View Invoice(s)",
		invoiceDate : "Invoice Date",
		due : "Due",
		dueDate : "Due Date",
		paymentStatus : "Payment Status",
		paymentDetails : "Payment Details",
		invOfPurOrder : "Invoices of Purchase Order",
		payOfInvNo : "Payments of Invoice No",
		paymentDate : "Payment Date",
		method : "Method",
		bankAccount : "Bank Account",
		loginDescription : "Please provide the below information",
		forgotPassword : "Forgot Password?",
		lblForgotPassword : "Forgot Password",
		userName : "User Name",
		password : "Password",
		logout : "Logout",
		enterInvoiceNo : "Enter Invoice Number",
		enterOrderNo : "Enter Purchase Order Number",
		enterValidNo : "Enter Valid Number",
		byPurchaseOrder: "By Purchase Order Number",
		byInvoiceNumber: "By Invoice Number",
		general : "General",
		companyProfile : "Company Profile",
		attachments : "Attachments",
		supplierName : "Supplier Name:",
		supplierNo : "Supplier Number:",
		registrationDate : "Registration Date:",
		renewalDate : "Renewal Date:",
		expirationDate : "Expiration Date:",
		legal : "Legal",
		genDirectorName : "General Director Name",
		activity : "Activity",
		partners : "Partners",
		partnership : "Partnership:",
		workplace : "Work Place",
		busClassification : "Business Classification",
		certificate : "Certificate",
		reference : "Reference",
		expDate : "Expiry Date",
		categoryName : "Cateogry Name",
		lastUpdateBy : "Last Update By",
		lastUpdateOn : 'Last Update On',
		enterLoginPassword : "Enter valid Email ID and Password",
		noRecordFound : "No record found",
		eventName : "Event Name",
		title : "Title",
		openDate : "Open Date",
		closeDate : "Close Date",
		price : "Price",
		Number : "Number",
		ticketNo : "Ticket No.",
		ticketDetails : "Ticket Details",
		subCategory : "Sub Category",
		createTicket : "Create New Ticket",
		selectDepartment : "Select Department",
		selectCategory : "Select Category",
		selectSubCategory : "Select Sub Category",
		all : "All",
		closed : "Closed",
		inProgress : "In Progress",
		reopen : "Reopen",
		registerTitle : "Register",
		enterHintText : "Enter ",
		contacts : "Contacts",
		bankDetails : "Bank Details",
		userAccount : "User Account",
		isUserRemovable : "Is User Removable",
		accountNumber : "Account Number",
		iban : "IBAN",
		currency : "Currency",
		bankName : "Bank Name",
		createTicket : "Create Ticket",
		viewTicket : "View Tickets",
		selectFederalEntity : "Select Federal Entity",
		others : "Others",
		SuppFederalEntity : "Supplier for Federal Entity",
		support : "Technical Support", 
		noDetailsFound : "No Details Found",
		getInvoices : "Get Invoices",
		getPayments : "Get Payments",
		takamulComingMsg : "Takamul is coming soon",
		imgTooBig : "Image too big for attachment",
		contactReqMsg : "Your contact request has been submitted successfully.",
		contactErroMsg : "Error occured while submitting your contact request.Please try again later.",
		imageLimitMsg : "You can select up to three documents at most",
		statusSubTickets : "Status of Submitted Tickets",
		noTicketFound : "No Ticket Found",
		createTicketMsg : "Do you you want to Create New Ticket?",
		supplierRegistration : "Supplier Registration",
		supplierEditRegistration : "Edit Profile",
		step1 : "Step 1",
		step2 : "Step 2",
		step3 : "Step 3",
		step4 : "Step 4",
		basicInfo : "Basic Information",
		companyDetails : "Company Details",
		companyNameAr : "Company Name (Arabic)",
		companyRegistrationNo : "Company Registration Number",
		companyNameEn : "Company Name (English)",
		contactInfo : "Contact Information",
		contactName : "Contact Name",
		mobileNumberColon : "Mobile No :",
		telephoneColon : "Telephone No :",
		basicClassification : "Basic Classifications",
		classification : "Classification",
		classicCertificate1 : "Chamber of Commerce membership Number (Certificate Number)",
		classicExpiryDate1 : "Chamber of Commerce membership Number (Expiration Date)",
		classicCertificate2 : "Commercial Registration Number (Certificate Number)",
		classicExpiryDate2 : "Commercial Registration Number (Expiration Date)",
		classicCertificate3 : "Trade License Number (Certificate Number)",
		classicExpiryDate3 : "Trade License Number (Expiration Date)",
		addressDetails : "Address Details",
		addressName : "Address Name",
		addressLine1 : "Address Line 1",
		addressLine2 : "Address Line 2",
		country : "Country",
		emirate : "Emirate",
		city : "City",
		poBox : "P.O.Box",
		registrationFees : "Pay Registration Renewal Fees",
		businessClassification : "Update Licenses",
		uploadNewDoc : "Upload New Documents",
		renewal : "Renew Supplier Registration",
		
		
		addressDesc : "Address Description",
		bankAccNo : "Bank Account No",
		bankName_branchName : "Bank Name/ Branch Name",
		additionalInfo : "Additional Information",
		companyAddInfo : "Company Additional Details",
		legalEntity : "Legal Entity",
		__selectLegalEntity : "-- Select Legal Entity --",
		generalDirectorNationality : "General Director's Nationality",
		__selectGeneralDirectorNationality : "-- Select General Director's Nationality --",
		generalDirectorName : "General Director's Name",
		attachmentDetails : "Attachments Details",
		certificateNumber : "Certificate Number",
		
				
		
		/*
		 * 
		 */
		selectCertificateDMethod :"Please select the certificate delivery method", 
		selectFinancialYear : "Please select the financial year", 
		enterCompanyName : "Please enter the organization Name",
		enterChamberOfCom : "Please enter the chamber of commerce",
		enterTradeLicenseNo : "Please enter the trade license number",
		plsSelectEmirate : "Please select the emirate",
		enterAddress : "Please enter the address",
		enterMobile : "Please enter the mobile number",
		invalidMobileNo : "Please enter a valid mobile number",
		invalidFaxNo : "Please enter a valid fax number",
		invalidPhoneNo : "Please enter a valid phone number",
		enterPOBox : "Please enter PO Box number",
		invalidPOBox : "Please enter a valid PO Box number",
		enterFirstName : "Please enter First Name",
		enterEmail : "Please enter email address",
		invalidEmail : "Please enter a valid email address",
		selectCountryIssued : "Please select the country issued for",
		selectPlaceOfIssue : "Please select the place of issuing the certificate",
		selectLanguage : "Please select the certificate language",
		enterNatureOfBusiness : "Please enter the nature of business",
		attachTradeLicense : "Please attach the valid trade license",
		attachSignedLetterCor : "Please attach the signed letter from the corporate",
		
		attachPassportCopy : "Please attach the passport copy",
		attachVisaCopy : "Please attach the visa copy",
		attachAuditCopy : "Please attach the copy of the audited financial accounts",
		attachLeaseCopy : "Please attach the lease copy",
		enterPassportNumber : "Please enter the passport number",
		selectNationality : "Please select the nationality",
		enterVisaNumber : "Please enter the visa number",
		enterNationalId : "Please enter the national id",
		enterWorkFor : "Please enter the work for",
		attachResidencyCopy : "Please attach the valid residence copy",
		attachSignedLetterCustomer : "Please attach the letter signed from the customer",
		attachEmployerLetter : "Please attach the letter from the employer",
		attachBankStatement : "Please attach the certified bank account statement for last 6 months",
		attachSalaryCertificate : "Please attach the valid salary certificate",
		attachEmployementContract : "Please attach a copy of the employment contract attested by the ministry of labour",
		vatTaxSuccess : "Your application submitted successfully",
		draft : "Draft",
		approval : "Approval",
		
		userType : "User Type",
		individual : "Individual",
		corporate : "Corporate",
		government : "Government",
		/*
		 * 
		 */
		
		certificateDelivery : "Certificate delivery method",
		financialYear : "Validity Start Date",
		financialYearNote : "The Certificate will be valid for one year from this date",
		companyName : "Organization Name",
		chamberOfCommerce : "Chamber of Commerce",
		tradeLicenseNo : "Trade License No.",
		emirate : "Emirate",
		seconadryMobile : "Secondary Mobile No.",
		countryIssuedFor : "Country Issued for",
		placeIssuingCertificate : "Place of Issuing the Certificate",
		certificateLanguage : "Certificate Language",
		natureOfBusiness : "Nature of Business",
		validTradeLicense : "Valid Trade License",
		signedLetter : "Signed Letter from the Corporate",
		passportCopyOwners : "Passport Copy for the Company Owners",
		visaCopyOwners : "Visa Copy for the Company Owners",
		copyAuditFinancialAccounts : "Copy of the Audited Financial Accounts",
		leaseCopy : "Lease Copy",

		certificateType : "Certificate Type",
		certificateDeliveryMethod : "Certificate delivery method",
		passportNo : "Passport No.",
		visNo : "Visa No.",
		nationalId : "National ID",
		workFor : "Work for",
		passportCopy : "Passport copy",
		validResidenceCopy : "Valid Residence Copy",
		letterSignedCustomer : "Letter Signed from the Customer",
		letterFromEmployer : "Letter from the Employer",
		certifiedBankAccount : "Certified Bank Account Statement for last 6 months",
		validSalaryCertiFicate : "Valid Salary Certificate",
		employementContract : "A copy of the employment contract attested by the Ministry of Labour",

		instruction1 : "Define the different sources of your Revenue , which will determine your Budget Limit.",
		instruction2 : "Name your Budget decide its Cycle and set its Start and End dates.",
		instruction3 : "Add the Expenses from the list of available Expenses which will form the 'Budget' part of each expense.",
		instruction4 : "Later on when you incur the expense, you can enter the 'Actual' value you spent.",
		instruction5 : "At any time, you are free to edit Budget elements.",

		contactContent : "This is Photoshop,s version of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet",
		phoneNumber : "Phone No",
		comments : "Comments",
		send : "Send",

		userCreatedSuccessMsg : "User created successfully.",
		userUpdatedSuccessMsg : "Profile updated successfully.",
		enterRevenueSourceTitleMsg : "Revenue Source Title",
		enterRevenueSourceValueMsg : "Revenue Source Amount",
		maximuAllowedResourcesCountReachMsg : "You have reached the maximum allowed resource sources count so you cannot add new source.",
		endDateCannotbeLess:"End date cannot be less than start date",
		userRegistration:"User Registration",
		changePassword:"Change Password",
		newPassword:"New Password",
		enterNewPassword:"Enter New Password",
		changePasswordSuccessMsg:"Youe password has been changed successfully.",
		//Reports
		fgFinalAccount:"Federal Final Account Reports",
	//	fgFinalAccount:"Final Account Reports",
		budgetExecutionRevenue:"Budget Execution By Revenue",
		budgetExecutionExpense:"Budget Execution By Expenses",
		budgetExecutionByCofog:"Budget Execution By COFOG",
		expenseRevenueKPI:"Budget Average KPI",
		expenseRevenueKPI : "Budget Average KPI",
		revenueAllocated : "Allocated Revenue",
		revenueExecuted: "Executed Revenue",
		expenditureAllocated:"Allocated Expenditure",
		expenditureExecuted:"Executed Expenditure",
		
		
		gfsReports:"GFS Reports",
		gfsReportsByRevenueAndExpense:"GFS Reports by Revenue and Expense",
		statementsOfGovtOperationsAssetsAndLiabilities:"Statements of Government Operations - Assets & Liabilities",
		statementsOfGovtOperationsIndices:"Statements of Government Operations - Indices",
		outlaysReportsFunctionsByGovt:"Outlays Reports Functions By Government",
		revenueAvg:"Revenue Average KPI",
		expenditureAvg:"Expenditure Average KPI",
		 dashBoard : "Dashboard",
		
		
		addnote:"add note here",
		confirmPassword : "Confirm Password",
		confirmPassMsg :"Password and Confirm Password should be same",
		confirmNewPassMsg :"New Password and Confirm Password should be same",
		enterValidMobile : "Enter valid mobile number",
		enterValidPhone : "Enter valid phone number",
		enterValidFax : "Enter valid fax number",
		codeTitle : "Code",
		noCategoryAvailable : "No budget categories available",
		enterValidPOBox : "Enter valid P.O. Box",
		deleteBudgetMsg : "Are you sure you want to delete this budget",
		expenseDateMsg : "Expense date should be in between budget dates :",
		budgetstartDateMsg : "Start Date should not be greater than budget start date : ",
		budgetEndDateMsg : "End date should not be less than budget end date : ",
		deleteBudget : "Delete Budget",
		NoExpenseCategory : "No Expense Category for this budget",
		PasswordValidMsg : "Password must contain at least 8 characters with one Number, one Capital and one Special character",
		spentAmount : "Spent Amount : ",
		viewMore : "More...",
		
		//takamul new 
		selectRequestType : "Select Request Type",
		details : "Details",
		createRequest : "Create Request",
		enterYourDetails : "Enter your details",
		theRespondent : "The Respondent:",
		theRespondentLoc : "The Respondent Location",
		requestList : "Request List",
		createNewRequest : "Create New Request",
		newUserRegister : "New User Registration",
		selectUserType : "Select User Type",
		selectCountry : "Select Country",
		enterUserName : "Enter User Name",
		enterEmailHint: 'Enter Email',
		enterMobileNo :"Enter Mobile No.",
		enterPasswordHint : "Enter Password",
		enterDetails : "Enter Details",
		userFeedback : "User Feedback",			
		enterComments : "Enter Comments",
		contactGov : "For Suggestions, Compliments and Customers Remarks please visit",
		selectAttachmentType : "Select Attachment Type",
		viewRequest : "View Request",
		reply : "Reply",
		replyRequest : "Reply Request",
		customerInquiry : "Customer Enquiry",
		firstSelectCategory : "Please select a Category first",
		
		
		
		mParticipation : "mParticipation",
		composeComment : "Compose Comment",
		compose : "Compose",
		personalDetails : "Personal Details",
		firstName : "First Name",
		mobileNo : "Mobile No",
		addMoreDetails : "Add more details",
		userSatisfaction : "User Satisfaction",
		userSatisfactionSuggestion : "Would you like to participate in a short Survey to evaluate the service?",
		thankYouUserSatisfaction : "Thank you for your contribution",
		feedback : "Feedback",
		skip : "No",
		emailAddress : "Email Address",
		mobileNumber : "Mobile Number",
		addNewUser : "Add New User",
		drafts : "Drafts",
		createdBy : "Created by",
		lastModified : "Last modified on",
		thankYouAddUser : "Request of adding new user has been sent.",
		lastName : "Last Name",
		emailAddressColon : "Email Address:",
		gender : "Sex",
		ageGroup : "Age Group",
		_selectNationality : "-- Select Nationality --",
		_selectGender : "-- Select Gender --",
		_selectAgeGroup : "-- Select Age Group --",
		commentAdded : "Your comment has been added.",
		addComment : "Add Comment",
		by : "by",
		ago : "ago",
		_selectEmirate : "-- Select Emirate --",
		bankDetails : "Bank Details",
		country : "Country",
		branchNo : "Branch Number",
		bankNo : "Bank Number",
		bankName : "Bank Name",
		branchName : "Branch Name",
		accountName : "Account Name",
	//	bankAccNo : "Bank Account Number",
		currency : "Currency",
		ibanNo : "IBAN Number",
		_selectCountry : "-- Select Country --",
		_selectBankName : "-- Select Bank Name --",
		_selectBranchName : "-- Select Branch Name --",
		_selectCurrency : "-- Select Currency --",
		contactDetails : "Contact Details",
		contactTitle : "Contact Title",
		_firstName : "First Name",
		middleName : "Middle Name",
		jobTile : "Job Title",
		__selectContactTitle : "-- Select Contact Title --",
		partnersDetails : "Partners Details",
		ownerName : "Owner Name",
		nationality : "Nationality", 
		partnership : "Partnership",
		citizenPartner : "Citizen partner work of place",
		_nationality : "-- Select Nationality --",	
		
		attachmentsDetails : "Attachment Details",
		text : "Text",
		_selectCategory : "-- Select Category --",
		
		
		//Location Federal
		locateFederal : 'Federal Entities Directory',
		direction : "Direction",
		steps : "Steps",
		from : "From",
		to : "To",
		totalDuration : "Total Duration",
		totalLength : "Total Length",
		
		//Open Financial Data
		lblFederalBudget : "Budget of Federal Government",
		gfsFederalUnion : "Budget of Federal Government",
		gfsRev_Exp : "Statements of Government Operations – Revenue & Expenses",
		gfsAsse_Lia : "Statements of Government Operations – Assets & Liabilities",
		gfsIndicies : "Statement of Government Operations – Analytic Indicators",
		gfsOutlays : "Government Outlays by Functions",
		description : "Description",
		total : "Total",
		code : "Code",
		revenue : "Revenue",
		expense : "Expense",
		value : "Value",
		budget : "Budget",
		
		
		// Dahsboard
		openFinancialData : "Open Financial Data",
		gccStatisticalBook : "GCC Statistical Book",
		customerInteraction : "Customer Interaction",
		mChatting : "mChatting",
		locationFedEntity : "Location of Federal entities",
		
		//open financial Data
		budgetExecutionGroupByRevenue : "Budget Execution Group By Revenue ",
		budgetExecutionGroupByExpenditure : "Budget Execution Group By Expenditure",
		budgetExecutionByRevenue : "Budget Execution Group By Revenue",
		budgetExecutionByExpenditure : "Budget Execution Group By Expenditure",
		budgetExecutionByCofog : "Budget Execution By COFOG",
		revenueKPI : "Revenue KPI",
		expenditureKPI : "Expenditure KPI",
		revenueExpenditureKPI : "Revenue/Expenditure KPI",
		assetsLiabilities : "Assets & Liabilities",
		revenueExpenses : "Revenue & Expenses",
		values : "Values",
		indicies : "Indices",
		cofogs : "COFOG",
		years : "Years",
		mof : "MOF",
		
		//Contact MOF
		detail : "Detail",
		map : "Map",
		abuDhabi : "Abu Dhabi",
		dubai : "Dubai",
		phone : "Phone",
		fax : "Fax",
		website : "Website", 
		sendMail : "Send Mail",
		mailAccountMsg : "Mail account not available.\nPlease check your email account settings.",
		
		
		// mSupplier Registration Validation
		
		enterCompanyEn : "Enter Company name in english",
		enterCompanyAr : "Enter Company name in arabic",
		enterCompanyRegNo : "Enter Company Registration Number",
		enterContactName : "Enter contact name",
		enterTelPhNo : "Enter telephone number",
		thankYouConfirmPayment : "Payment is completed successfully.",
		paymentFailure : "Payment got Failed",
		invalidRegisterNo : "Registration number should be numeric",
		invalidTelPhoneNo : "Telphone number should be numeric",
		mSuppFirstName : "Enter first name",
		
		enterAddressName : "Enter address name",
		enterAddressLine1 : "Enter address line1",
		enterAddressLine2 : "Enter address line2",
		selectEmirate : "Select emirate",
		enterCity : "Enter city",
		mSupEnterPOBox : "Enter P.O.Box",
		mSupInvalidPOBox : "Enter valid P.O.Box",
		enterBankAccountNo : "Enter bank account number",
		enterAccountName : "Enter account name",
		selectBranchName : "Select branch name",
		selectBankName : "Select bank name",
		selectCountryName : "Select country name",
		
		selectCurrency : "Select currency",
		enterIBANNo : "Enter IBAN number",
		enterMiddleName : "Enter middle name",
		enterJobTitle : "Enter job title",
		enterGeneralDirectorName : "Enter general director's name",
		selectLegalEntity : "Select legal entity",
		selectGeneralDirectorNationality : "Select general directory nationality",
		selectActivity : "Select atleast one activity",
		enterPartnerDetails : "Enter partner details",
		enterOwnerName : "Enter owner name",
		enterPartnership : "Enter partnership in percentage",
		invalidPartnership : "Partnership should be in integer",
		enterCitizenPartner : "Enter citizen partner",
		mSupSelectNationality : "Select nationality",
		enterTitle : "Enter Title",
		selectAttachment : "Select Attachment",
		addressMandatory : "At least one address field is required.",
		companyMandatory : "All fields are mandatory",
		bankMandatory : "At least one bank field is required.",
		activityMandatory : "At least one activity field is required.",
		partnerMandatory : "Total of Partnership percentage should be 100.",
		cannotAddNewPartner:"Partnership percentage reached to 100. You cannot add new partners",
		partnerShipMaxValueCanEnter:"Maximum value that could be entered is:",
	
		spent : "Spent",
		expenses : "Expenses",
		assets : "Assets",
		
		allocatedRevenue : "Allocated Revenue",
		executedRevenue : "Executed Revenue",
		allocatedExpenditure : "Allocated Expenditure",
		executedExpenditure : "Executed Expenditure",
		
		enterConfirmPasswordHint : "Enter Confirm Password",
		enterAddressHint : "Enter Address",
		enterName : "Please enter the user name",
		
		enterPassword : "Please enter the password",
		enterNewPassword : "Please enter the new password",
		enterConfirmPassword : "Please enter the confirm password",
		enterEmail : "Please enter the email address",
		invalidUserType : "Please select the user type",
		enterAnswer : "Please enter answer",
		next : "Next",
		logOutMessage : "Are you sure you want to Logout?",
		enterEmailAddress : "Enter Email Address",		
		selectMaximiumFive : "You can select up to one documents at most",
		exitRegistration : "Are you sure you want to exit Registration?",
		fillAddressDetails : "Please fill address details.",
		fillBankDetails : "Please fill bank details.",
		fillContactDetails : "Please fill contact details.",
		enterCerNo1 : "Please enter Chamber of Commerce membership number.",
		enterExp1 : "Please select Chamber of Commerce membership expiration date.",
		enterCerNo2 : "Please enter Commercial Registration number.",
		enterExp2 : "Please select Commercial Registration expiration date.",
		enterCerNo3 : "Please enter Trade License number.",
		enterExp3 : "Please select Trade License expiration date.",
		
		deleteAttachment : "Are you sure you want to delete attachment?",
		dataSuccess : "Details successfully updated.",
		incorrectAnswer : "Incorrect answer",
		cameraNotAccess : "This app does not have access to your camera",
		camera : "Camera",
		oldPassword : "Old Password",
		enterOldPassword : "Please enter the old password",
		noDataAvailableAtTheMoment:"No data available at this moment.",
		answer : "Answer",
		createNewAccount : "Create New Account",
		registration : "Registration",
		retry : "Retry",
		
		
		//
		
		transactionId : "Transaction Id",
		transactionAmount : "Transaction Amount",
		confirmationId : "Confirmation Id",
		confirmationDate : "Confirmation Date",
		enterValidCompanyAr : "Company name should be in Arabic",
		partnerShipGreater : 'Partnership percentage should not exceed 100',
		
		// Today :
		
		editRegistration : "Edit Registration",
		newResumeRegistration : "New/Resume Supplier Registration",
		
		
		
		invalidName : "Please enter the valid name",
		invalidCompanyName : "Please enter the valid company name",
		invalidChamberOfCom : "Please enter the valid chamber of commerce",
		invalidAnswer : "Please select at least one answer to submit",
		notAccessRenewal : "Your annual Registration will expire after more than one month . Are you sure you want to renew ?",
		
		
		// 
		invalidTelNo : "Please enter valid phone number",
		enterPhoneNumber : "Please enter the phone number",
		pay : "Pay Fees",
		invalidPhNo : "Telphone number should be numeric",	
		resumeRegistration : "Resume Registration",
		securityQuestion : "Security Question",
		invalidSecurityQuestion : "Please enter at least 3 answer",
		select : "Select ",
		serviceDescription : "Service Description",
		serviceProcessing : "Service Processing",
		apply : "Apply",
		enterSubject : "Please enter the subject",
		plsEnterComments : "Please enter the comments",
		plsSelectRequestType : "Please select feedback type",
		sQuestionSelected : "Done",
		notAccessDropbox : "You cannot use Dropbox",
		attachmentNote : "Please select the attachment either from Dropbox or from Camera/Gallery",
		renewFees : "Renewal",
		invalidCompose : "Please provide comments to submit",
		selectFeedbacktype : "Select Feedback Type",
		englishNumberMandatory : "All numbers must be entered in English", 
		stepsMandatory1 : "Please save any changes you make",
		stepsMandatory2 : "before leaving the page",
		
		endDate : "Open for participation until: ",
		mSupplierReminderMsg : "The information you will enter here are critical. Therefore, please ensure they are accurate, especially e-Mail addresses. Thank you",
		mSupplierReminderTitle : "Reminder",
		proceed : "Proceed",
		languageInstruction : "From the below listed languages, please select the language that will be used to issue the Certificate:",
		
		feesPayment : "Fees Payment",
		paymentMsg : "You will be directed to e-Dirham payment gateway to pay your fees",
		deletePartner : "Are sure you want to delete this Partner?",
		deleteActivity : "Are sure you want to delete this Activity?",
		add : "Add",
		
		officialLetter :"Official Letter Intended to MoF",
		establishmentDecree : "Federal Decree of Establishment",
		attachOfficialLetter : "Please attach the Official Letter Intended to MoF",
		attachEstablishment : "Please attach the Federal Decree of Establishment",
		
	};
	return english;
};
