exports.language = function() {
	var arabic = {
		appTitle : "أم القيوين الذكية",
		english : "English",
		englishLF : "english",
		arabicLF: "arabic",
		news : "أخبار",
		events : "أحداث",
		departments : "الدوائر الحكومية",
		workingHour : "ساعات العمل",
		contactUs : "اتصل بنا",
		location : "الموقع",
		enterLandmark : "أدخل المعلم خاصتك",
		suggestions : "الفئة",
		comments : "تعليقات",
		firstName : "الاسم الأول",
		lastName : "اسم العائلة",
		emailAddress : "البريد الإلكتروني",
		emailAddressConfirm : "تأكيد عنوان البريد الإلكتروني",
		submit : "إرسال",
		capSignIn : "تسجيل دخول",
		capRegister : "تسجيل",
		skip : "تجاوز",
		forgotPassword : "نسيت كلمة السر",
		userName : "اسم المستخدم",
		password : "كلمة المرور",
		overviewCap : "نظرة عامة",
		theRulerCap : "الحاكم",
		crownPrinceCap : "ولي العهد",
		crown:"ولي العهد",
		departmentCap : "الدوائر الحكومية",
		favourite : "المفضلة",
		happinessTitle : "ما تقييمك لخدماتنا؟",
		notificationTitle : "حالة طلباتي",
		left : "يسار",
		right : "يمين",
		on : "تشغيل",
		off : "إيقاف",
		send : "إرسال",
		registration : "تسجيل",
		fullName : "الاسم الكامل",
		nationality : "الجنسية",
		dob : "تاريخ الميلاد",
		nationalId : "رقم الهوية الأمارتية",
		confirmPassword : "تأكيد كلمة المرور",
		mobile : "رقم الموبايل",
		subscription : "اشتراك",
		login : "تسجيل دخول",
		logout : "تسجيل خروج",
		services : "خدمات",
		citizenCap : "الأفراد",
		businessCap : "الشركات",
		weatherCity : "أم القيوين، الإمارات العربية المتحدة",
		weatherType : "مشمس",
		feedback : "إقتراحاتي",
		
		home : "الصفحة الرئيسية",
		myservices : "خدماتي",
		edit : "تعديل",
		username : "اسم المستخدم",
		menuDirectiion : "اتجاه القائمة",
		notification : "الإشعارات",
		dropbox: "مربع الهبوط",
		mobile : "رقم موبايل مسجل",
		emiratesid : "رقم التعريف الإماراتي",
		passport : "رقم جواز السفر",
		license : "رقم الرخصة",
		submit : "إرسال",
		mail : "عنوان البريد الإلكتروني",
		forgotUsername : "نسيت اسم المستخدم",
		individual : "فرد",
		establishment : "مؤسسة",
		open : "فتح",
		loading : "تحميل ...",
		updating : "جار تحديث ...",
		cancel : "إلغاء",
		registration : "تسجيل",
		individualCitizenLbl : "فرد - مواطن اماراتي",
		individualResidentLbl : "فرد - مقيم في دولة الامارات",
		individualGccCitizen : "فرد - مواطن خليجي",
		individualGccResident : "فرد - مقيم ",
		indivlVisitor : "فرد - زائر",
		establishmentReg : "مؤسسة",
		fullName : "الاسم كاملا",
		fullNameHintText: "(كما هو مدون في بطاقة التعريف الاماراتية)",
		countryResidence : "بلد الاقامة",
		mobileNum : "رقم الموبايل 1",
		mobileNum2 : "رقم الموبايل 2",
		landlineNum : "رقم الهاتف",
		establishNameAsStated: "اسم المؤسسة",
		hintTextEstFullnamelbl: "(كما هو مدون في الترخيص التجاري)",
		dob : "تاريخ الميلاد",
		nationalId : "رقم الهوية الأمارتية",
		nationalIdExpiry : "تاريخ أنتهاء الهوية الأمارتية",
		confirmPassword : "تأكيد كلمة المرور",
		mobile : "رقم الموبايل",
		emiratedId : "الهوية الاماراتية",
		chooseEmirates : "الامارة",
		emiratedIdFrontAttch : "الوجه الامامي للهوية الاماراتية",
		emiratedIdBackAttch : "الوجه الخلفي للهوية الاماراتية",
		passportNum : "رقم جواز السفر",
		passportFrontAttach : "الصفحة الأولى لجواز السفر",
		accountDetailsSplit : "تفاصيل الحساب",
		credentialsSplit : "اوراق الاعتماد",
		idInformationSplit : "بيانات الهوية",
		passportInformatioinSplit : "بيانات جواز السفر",
		familyBookSplit : "بيانات دفتر العائلة",
		hasFamilyBook : "أمتلك دفتر عائلة ",
		fullNameBook: "الاسم كاملا",
		hintBookFullname: "(كما هو مدون في خلاصة القيد)",
		townName : "اسم المدينة",
		townNumber : "رقم المدينة",
		familyNumber : "رقم العائلة",
		tribeName : "اسم القبيلة",
		clanNumber : "الرقم العائلي",
		issueDateBook : "تاريخ الاصدار",
		motherNameTxt : "اسم الأم",
		motherFatherNameTxt : "اسم والد الأم",
		familyBookAttch : "دفتر العائلة",
		fullnamePassport: "الاسم كاملا",
		hintTxtPassPostName : "(كما هو مدون في جواز السفر)",
		visapagetxt : "صفحة التأشيرة",
		
		passportResidentpage : "صفحة الاقامة في جواز السفر",
		subscription : "الاشتراك",
		subscriptionReg : "اشترك لاستلام النشرة الاخبارية",
		CompleteRegProcess : "اتمام عملية التسجيل",
		OTPtxt : "كلمة المرور",
		sendAnotherOTP : "اعادة ارسال رمز تفعيل جديد",
		activateAccount : "تفعيل حساب المستخدم",
		activateAcounttxt : "تفعيل حساب",
		individualUserTxt : "الفرد",
		establishUserTxt : "المؤسسة",
		mobilenumberHinttxt : "رقم الموبايل",
		emiratesIDorPassport : "الهوية الاماراتية او رقم جواز السفر",
		tradeLicenceNumber : "رقم الترخيص التجاري",
		
		
		fullNameActivation : "الاسم كاملا",
		establishNameLbl : "اسم المؤسسة",
		tradeLicenceLbl : "الترخيص التجاري",
		signatureAttest : "تصديق الموقعون",
		tradeLicenExpiryDate : "تاريخ انتهاء الترخيص التجاري",
		tradeLicenseType : "نوع الترخيص التجاري",
		officePhoneLabel : "رقم هاتف المكتب",
		addressLabelen : "العنوان",
		websiteLabelEn : "الموقع الالكتروني",
		postBoxLabel : "صندوق البريد",
		fileSizeExceed : "تم تجاوز الحد الأقصى لحجم الملف",
		passwordValidate : "كلمة السر المستخدمة امنه بشكل متوسط ",
		passwordValidate2: " كلمة السر يجب أن تتكون من 8 إلى 15 حرف",
		passwordValidate3: "لابد أن تحتوي الباسورد على حرف كبير ورقم وحرف خاص",
		userNameValid : "لا يسمح للأحرف العربية, والأحرف الخاصة, أو اضافة مساحة", // to do
		fullNameValid : "لا يسمح للأحرف خاصة وأرقام .",
		weakTxt:"القوة: ضعيف",
		mediumTxt:"متوسطة: القوة‎",
		strongTxt : "القوة: قوي",
		plzCountryOfCitizenship : "الرجاء اختيار بلد الجنسية",
		plzCountryOfResidence : "الرجاء اختيار بلد الاقامة",
		plzMobileNumber : "الرجاء ادخال رقم الموبايل",
		plzOfficephone : "الرجاء ادخال رقم هاتف المكتب",
		plzEmailAddress : "الرجاء ادخال عنوان البريد الالكتروني",
		plzAddressEstablish : "الرجاء ادخال العنوان",
		plzWebsiteValue : "الرجاء ادخال عنوان الموقع الالكتروني",
		plzUserName : "الرجاء ادخال اسم المستخدم",
		plzPassword : "الرجاء ادخال كلمة السر",
		plzFullNameIndiv : "الرجاء ادخال الاسم كاملا",
		plzEmiratesId : "الرجاء ادخال رقم الهوية الاماراتية",
		plzValidEmiratesId : "الرجاء إدخال إمارات صالح معرف",
		plzChooseEmirates : "الرجاء اختيار إمارة",
		plzPostBox : "الرجاء ادخال رقم صندوق البريد",
		plzPostBoxvalid : "الرجاء ادخال صندوق البريد",
		plzTradeLicNum : "الرجاء ادخال رقم الترخيص التجاري",
		plzTradeLicExpiry : "الرجاء ادخال تاريخ انتهاء صلاحية الترخيص التجاري",
		plzChooseTradeLicType : "الرجاء اختيار نوع الترخيص التجاري",
		plzAttachTradeLic : "الرجاء ارفاق الترخيص التجاري",
		plzAttachSignature : "الرجاء ارفاق التوقيع",
		plzEmiratesExpdate : "الرجاء اختيار تاريخ أنتهاء الهوية الأمارتية",
		plzChooseDOB : "الرجاء اختيار تاريخ الميلاد",
		plzEmiratedIDfrontAttch : "الرجاء ارفاق الوجه الامامي للهوية الاماراتية",
		plzEmiratesIdBackAttch : "الرجاء ارفاق الوجه الخلفي للهوية لاماراتية",
		plzPassportNum : "الرجاء ادخال رقم جواز السفر",
		plzAttchPassportFront : "الرجاء ارفاق الصفحة الامامية لجواز السفر",
		plzPassportNamefull : "الرجاء ادخال الاسم كاملا كما هو مدون في جواز السفر",
		plzPassportVisaPage : "الرجاء ارفاق صفحة الاقامة في جواز السفر",
		plzEstablishName : "الرجاء ادخال اسم المؤسسة",
		plzAttchPassportResident : "الرجاء ارفاق صفحة الاقامة في جواز السفر",
		plzFullnameBook : "الرجاء ادخال الاسم كاملا كما هو مدون في دفتر عالعائلة",
		plzCooseEmirtesBook : "الرجاء اختيار إمارة دفتر العائلة",
		plzTownNameBook : "الرجاء ادخال اسم المدينة كما هو في دفتر العائلة",
		plzTownNumber : "الرجاء ادخال رقم المدينة كما هو في دفتر العائلة",
		plzFamilyNumber : "الرجاء ادخال رقم العائلة كما هو في دفتر العائلة",
		plzTribeName : "الرجاء ادخال اسم القبيلة كما هو في خلاصة القيد",
		plzClanNumber : "الرجاء ادخال الرقم العائلي كما هو في دفتر العائلة",
		plzChooseIssuedateBook : "الرجاء اختيار تاريخ اصدار دفتر العائلة",
		plzMotherName : "الرجاء ادخال اسم الام كما هو في دفتر العائلة",
		plzMotherFatherName : "الرجاء ادخال اسم والد الام كما هو في دفتر العائلة",
		plzAttchFamilyBook : "الرجاء ارفاق دفتر العائلة",
		passwordMisMatch : "لم تتطابق كلمة السر",
		noRecordsFound : "لا يوجد نتائج",
		uploadDocSuccess : "تم تحميل المستند بنجاح",
		enterValidEmail : "الرجاء ادخال بريد الكتروني صحيح",
		emailNotMatch : "لا يتطابق ​تأكيد عنوان البريد الإلكتروني",
		enterValidMobile : "الرجاء ادخال رقم موبايل صحيح",
		enterValidlandline: "الرجاء ادخال رقم هاتف صحيح",
		enterValidofficePhone : "الرجاء ادخال رقم هاتف صحيح",
		registrationSuccessful : "تم التسجيل بنجاح",
		plzEmiratesOrPassportId : "الرجاء ادخال رقم الهوية الاماراتية او جواز السفر",
		yourAccountIsNotVerified : "لم يتم التحقق من حسابك، يرجى المحاولة لاحقا",
		plzEnterOTP : "الرجاء ادخال كلمة المرور التي وصلتك على هاتفك",
		validateYouraccountOTP : "لم تقم بتفعيل حسابك",
		nationality : "بلد الجنسية",
		uploadDocfailed : "فشل في تحميل الملف",
		weatherCity : "أم القيوين، الإمارات العربية المتحدة",
		weatherType : "مشمس",
		0 : "إعصار",
		1 : "عاصفة إستوائية",
		2: "زوبعة",
		3: "عواصف رعدية شديدة",
		4: "عواصف رعدية",
		5: "امطار وثلوج",
		6: "امطار وصقيع",
		7: "ثلوج وصقيع",
		8: "رذاذ متجمد",
		9: "رذاذ",
		10: "امطار متجمدة",
		11: "أمطار غزيرة",
		12: "أمطار غزيرة",
		13: "هبات الثلوج",
		14: "زخات الثلوج خفيفة",
		15: "ثلوج عاصفة",
		16: "ثلج",
		17: "برد",
		18: "صقيع",
		19: "غبار",
		20: "ضبابي",
		21: "ضباب",
		22: "مفعم بالدخان",
		23: "متهيج",
		24: "عاصف",
		25: "بارد",
		26: "غائم",
		27: "غائم كلياً",
		28: "غائم كلياً",
		29: "غائم جزئيا",
		30: "غائم جزئيا",
		31: "صافي",
		32 : "مشمس",
		33 : "مقبول",
		34 : "مقبول",
		35 : "امطار وبرد",
		36 : "حار",
		37 : "عواصف رعدية معزولة",
		38 : "عواصف رعدية متفرقة",
		39 : "عواصف رعدية متفرقة",
		40 : "أمطار غزيرة متفرقة",
		41 : "ثلوج كثيفة",
		42 : "زخات الثلوج المتناثرة",
		43 : "ثلوج كثيفة",
		44 : "غائم جزئياً",
		45 : "عواصف رعدية",
		46 : "ثلوج قوية",
		47 : "عواصف رعدية معزولة",
		3200 : "غير موجود",
		
		aboutUAQ : "عن أم القيوين",
		//feedback : "أراء",
		funeral : "جنائز أم القيوين",
		home : "الصفحة الرئيسية",
		mysuggestions : "مدينتى",
		myservices : "خدماتي",  // to do update this arabic text
		edit : "تعديل",
		menuDirection : "اتجاه القائمة",
		notification : "الإشعارات",
		mobile : "رقم موبايل مسجل",
		emiratesid : "الهوية الاماراتية",
		passport : "رقم جواز السفر",
		license : "رقم الرخصة",
		submit : "إرسال",
		mail : "عنوان البريد الإلكتروني",
		forgotUsername : "نسيت اسم المستخدم",
		individual : "الفرد",
		establishment : "المؤسسة",
		sendMail : "ارسال بريد الكتروني",
		mailAccountMsg : "البريد الالكتروني غير متاح. الرجاء التحقق من اعدادات حساب بريدك الالكتروني",
		open : "فتح",
		webURLMsg : "غير قادر على فتح الموقع الالكتروني",
		enterUserName : "ادخال اسم المستخدم",
		enterEmiratesId : "ادخال رقم الهوية الاماراتية",
		passportNumber : "ادخال رقم جواز السفر",
		mobileNumber : "ادخال رقم الموبايل",
		licenseNumber : "ادخال رقم الرخصة",
		mailId : "الرجاء ادخال عنوان بريد الكتروني صحيح",
		enterFirstName : "ادخال الاسم الاول",
		enterLastName : "ادخال الاسم الاخير",
		//submitFeedback : "ارسال الاّراء", - Not used now >NIKUNJ
		forgetPassword : "نسيت كلمة السر",
		invalidmail : "عنوان البريد الإلكتروني غير صحيح",
		government : "دائرة الحكومة الالكترونية",
		enterComments : "ادخال التعليق",
		submitRating : "شكرا لتقييمكم خدماتنا",
		submitThanks : "شكراً لإرسال إقتراحاتكم‎",
		ruler : "الحاكم",
		overView : "نبذة  ",
		department : "الدوائر الحكومية",
		favourite : "مفضلات",
		description : "الوصف",
		submitTime : "وقت الارسال",
		serviceBeneficiary : "المستفيد من الخدمة",
		requiredDocuments : "المستندات المطلوبة",
		procedures : "الاجراءات",
		servicesFees : "رسوم الخدمات",
		startService : "بدء الخدمة",
		uaqJnazah : "جنائز أم القيوين",
		plzEnterUserName : "الرجاء ادخال اسم المستخدم",
		plzEnterPassword : "الرجاء ادخال كلمة السر",
		youAccountisActive : "الحساب مفعل سابقا. الرجاء تسجيل الدخول",
		welcomeGuest : "مرحبا",
		proApplicationFee : "تابع إلى دفع تكاليف الطلب",
		procServiceFeep : "تابع إلى دفع تكاليف الخدمة",
		resubmit : "إعادة الإرسال",
		proReviewer : "المتابعة للمراجع",
		subNOC : "شكرا لإرسال عدم الممانعة",
		subLicense : "ادخال الرخصة",
		addFavourites : "تمت الإضافة إلى المفضلة",
		removeFavourites : "تمت الإزالة من المفضلة",
		dismiss : "إلغاء",
		view : "اظهار",
		generic : "حول UAQ",
		device_regi_error : "توجد مشكلة في إرسال المعلومات. الرجاء المحاولة لاحقا",
		internet_err : "تأكد من اتصالك بالإنترنت",
		zero_val : "0",
		no_details_found : "لا توجد تفاصيل",
		contactsCustomerService : "الاتصال بخدمة العملاء",
		serviceRequestForm : "يتم طلب الخدمة من:",
		no_notification : "لا توجد أي اشعارات حاليا",
		exitConfirm : "هل أنت متأكد من إغلاق التطبيق؟",
		
		
		welcome : "أهلا و سهلا",
		proApplicationFee : "تابع إلى دفع تكاليف الطلب",
		procServiceFeep : "تابع إلى دفع تكاليف الخدمة",
		resubmit : "إعادة الإرسال",
		proReviewer : "المتابعة للمراجع",
		subNOC : "شكرا لإرسال عدم الممانعة",
		subLicense : "ادخال الرخصة",
		toissueSiteplan : "إلى إصدار خطة الموقع", // to do arabic
		valid_last_name : "ينبغي على اسم العائلة أن يتضمن الحروف الهجائية فقط",
		valid_first_name : "ينبغي على الاسم الأول أن يتضمن الحروف الهجائية فقط",
		login_access_eServices : "الرجاء قم بتسجيل الدخول حتى تستطيع الوصول إلى إشعارات الخدمات",
		suggestion_sent_failed : "فشل في ارسال اقتراحك. الرجاء المحاولة لاحقا",
		suggestion_sent : "تم إرسال اقتراحك بنجاح",
		photo_uploaded : "تم تحميل الصورة بنجاح",
		photo_upload_failed : "فشل في تحميل الصورة",
		blank_suggestion : "الرجاء اختيار الفئة",
		blank_comment : "الرجاء ادخال تعليقك",
		valid_email_err : "الرجاء ادخال بريد الكتروني صحيح",
		fname_req : "الرجاء ادخال الاسم الاول",
		lname_req : "الرجاء ادخال اسم العائلة",
		email_req: "الرجاء إدخال البريد الإلكتروني.",
		shareTwitterSuccess : "تمت المشاركة على تويتر",
		duplicateMessage : "تمت المشاركة على تويتر سابقا",
		shareTwitterFail : "لم تتم المشاركة على تويتر. الرجاء المحاولة لاحقا",
		invalidMobile : "رقم الموبايل يتكون من أرقام فقط",
		invalidEmiratesId:"الرجاء إدخال 15 أرقام من هيئة الإمارات للهوية",
		mobileLength : "الرحاء ادخال رقم موبايل من عشرة أرقام",
		allowAlphabets : "الرجاء ادخال أحرف فقط",
		facebook : "فيسبوك",
		twitter : "تويتر",
		share : "مشاركة؟",
		mail : "",
		mail_forgotUsername : "البريد الالكتروني",
		ramadan : "رمضان",
		viewMore : "اظهار المزيد",
		validateHintText : "الرجاء قم بإدخال إما رقم الهوية الإماراتيه أو رقم جواز السفر",
		fbShare : "المشاركة على فيسبوك",
		twitterShare : "المشاركة على تويتر",
		submittedRating :"لقد مصنفة بالفعل طلبنا . شكرا لأفادتك",
		viewMore : "مشاهدة المزيد",
		comingSoon : "قريبا",
		reminder : "تذكير",
		or : "أو",

		arabic : "عربي",
		back : "إلى الوراء",
		changeLanguage : "تغيير",
		call : "اتصال",
		callConformAlert : 'هل تريد الإتصال؟',
		noCallAlert : 'خدمة الإتصال ليس متاحة',
		ok : "تم",
		serviceError : 'الخدمة غير متاحة حاليا, يرجى إعادة المحاولة',
		doneTitle : "تم",
		error : 'خطأ',
		language : "تغيير اللغة",
		noInternet : "لا يوجد اتصال بالإنترنت",
		networkError : "خطأ في الشبكة",
		preferMenuDirection : "الرجاء اختيار اتجاه القائمة",
		not_reg_push_error : "أنت غير مسجل لاستلام الإشعار، يرجى المحاولة مرة أخرى أو إعادة تشغيل التطبيق.",
		push_subscribe_success : "تم الإشتراك في خدمة الإشعارات بنجاح. ",
		push_unsubscribe_success : "تم إلغاء خدمة الإشعارات بنجاح.",
		suggestionPicLimit : "لا تستطيع ارسال أكثر من مرفق واحد.",
		leave_from_suggestion : "هل تريد الخروج قبل إرسال اقتراحك",

		indivlVisitor : "فرد - زائر",
		fullNameHintText : "(كما هو ظاهر في بطاقة الهوية الإماراتيه)",
		passportInformatioinSplit : "معلومات الجواز",
		hintBookFullname : "(كما هو مدون في دفتر العائلة)",

		cameraNotAvail : "الكاميرا غير متاحة",
		useCamera : "استخدام الكاميرا",
		selectFromGallery : "الاختيار من المعرض",
		attachMedia : "ارفاق صورة أو فيديو",
		cameraNotAccess : "التطبيق لا يستطيع الوصول إلى الكاميرا",
		camera : "الكاميرا",

		actionBtn : "حركة",
		proCardRequest : "طلب بطاقة مندوب",
		landDemarkation : "تعيين حدود الأرض",
		extenGrandLand : "تمديد طلب منحة أرض",
		addLand : "إضافة أرض",
		country : "الجنسية",

		shareFBSuccess : "تمت المشاركة على الفيسبوك بنجاح",
		facebookCancel : "تم إلغاء تقاسم الفيسبوك",
		shareFBFail : "لا نستطيع المشاركة على فيسبوك. الرجاء المحاولة لاحقا",

		photoupload_info : "قم بتحميل صورة بالضغط على زر (+).",
		yes:"نعم‎",
		no:"لا‎",
		skip_login_step:"هل تريد تخطي عملية تسجيل الدخول؟",
		
		servicePayment : "موقع الدفع",
		serviceAmount : "الرسوم",
		serviceDescription : "وصف",
		location_not_determined:"لا يمكن تحديد موقعك، يرجى المحاولة مرة أخرى.",
		mobileNo:"رقم الجوال",
		turn_on_location_service:"يرجى تفعيل خدمة الموقع في اعدادات النظام للجهاز​",
		error_loading_eService_page:"حدث خطأ أثناء تحميل صفحة الخدمة",
		// Terms and Condtion
		agreetoTermsCond : "أوافق على الشروط والأحكام‎",
		plzAgreeTheTerms : "يرجى الموافقة على الشروط والأحكام",
		termsAndCondition : "الشروط والأحكام",
		accept : "قبول",
		decline : "رفض",
		termsPersonaldata:"البيانات الشخصية التي تم جمعها هي",
		termsPersonaldata1:"​.		​الاسم الكامل",
		termsPersonaldata2:".		تفاصيل شخصية",
		termsPersonaldata3:".		​البريد الالكتروني​",
		termsPersonaldata4:".		رقم الهاتف",
		termsPersonaldata5:".		معلومات الرخصة التجارية (سجل كمؤسسة )",
		termsPersonaldata6:".		الموقع الجغرافي",
		termsPersonalDetails:"​يتم جمع المعلومات الشخصية عند التسجيل أو أثناء استخدام ملاحظات أو اقتراحات بلدي الخدمات التي تقدمها الوكالة SmartUAQ ويمكن استخدامها لتقديم طلب للحصول على الخدمات التي يقدمها التطبيق​",
		termsDataControler : "مالك ومتحكم البيانات",
		termsDataContolerDesc : "​يتم تشغيل الخدمات من قبل الحكومة الالكترونية لام القيوين، محكمة الأميري، أم القيوين، الإمارات العربية المتحدة.حكومة أم القيوين هي المتحكمة عن البيانات الشخصية التي يتم جمعها ومعالجتها واستخدامها والمصرح عنها أو نقلها فيما يتعلق بالخدمات.​",
		termsDataCollection : "أنواع البيانات التي تم جمعها​",
		termsDataCollectionDesc : "​البيانات الشخصية يمكن تقديم بحرية من قبل المستخدم، ما لم ينص على خلاف ذلك، ويعمل على تحديد المستخدمين وتذكر تفضيلاتهم، لغرض وحيد هو توفير الخدمة المطلوبة من قبل المستخدم.​ ",
		termsMethodOfProcess :"طرق المعالجة",
		termsMethodProcessDes : "​مراقب البيانات يعالج البيانات من المستخدمين بطريقة سليمة، وتتخذ التدابير الأمنية المناسبة لمنع الوصول غير المصرح به، والكشف، وتعديل، أو التدمير غير المصرح به للبيانات.​",
		termsPlace : "المكان",
		termsPlaceDes : "​تتم معالجة البيانات في مكاتب التشغيل وحدة تحكم البيانات، وفي أي أماكن أخرى حيث توجد الأطراف المعنية مع المعالجة.​",
		termsRetentionTime : "وقت الاحتفاظ​",
		termsRetentionTimeDes : "​يتم الاحتفاظ بيانات عن الوقت اللازم لتقديم الخدمة المطلوبة من قبل المستخدم، أو جاء على لسان أغراض المبينة في هذه الوثيقة.​",
		termsUseCollectionData : "استخدامات البيانات التي تم جمعها​",
		termsUseCollectionDataDes : "​يتم جمع البيانات المتعلقة للعضو للسماح للمالك لتقديم خدماته، وكذلك للأغراض التالية: التفاعلات القائمة على الموقع.​",
		termsLegalAction : "اجراءات قانونية",
		termsLegalActionDes : "​المستخدم يعلن أن تكون على علم بأن المراقب المالي البيانات قد تكون هناك حاجة لكشف البيانات الشخصية بناء على طلب من السلطات العامة.​",
		termsLogmaintain : "سجلات النظام والصيانة",
		termsLogmaintainDes : "​لأغراض التشغيل والصيانة، وهذا التطبيق وأي خدمات طرف ثالث قد جمع الملفات التي سجل التفاعل مع هذا التطبيق (سجلات النظام).​",
		termsInformationNotContain : "المعلومات غير واردة في هذه السياسة",
		termsInformationNotContainDes : "قد يطلب المزيد من التفاصيل بشأن جمع أو معالجة البيانات الشخصية من وحدة تحكم البيانات في أي وقت. يرجى الاطلاع على معلومات الاتصال +9716764100​ ",
		termsUAQGovt : "إن دائرة الحكومة الالكترونية لأم القيوين لن تكشف عن المعلومات الشخصية لأطراف ثالثة، باستثناء ما هو منصوص عليه أدناه:​",
		termsUAQGovtDes1 : "​- عند الطلب منها ذلك بموجب القانون",
		termsUAQGovtDes2 : " - في اتصال مع أية إجراءات قانونية.​",
		termsChPrivacy : "تغييرات على سياسة الخصوصية",
		termsChPrivacyDes : "​تحتفظ تحكم بيانات بالحق في إجراء تغييرات على سياسة الخصوصية هذه في أي وقت عن طريق إعطاء إشعار لمستخدميها.​",
		termsNotes : "يجب على المستخدم أن لا يوفر أي معلومات كاذبة مضللة أثناء التسجيل. اذا حدث هذا فان حكومة أم القيوين لها الحق في اتخاذ الإجراءات القانونية ضد فرد أو مؤسسة*",
		next:"التالي",
		help:"أرشادات التطبيق",
		end:"النهاية",
		shareapp:"شارك التطبيق؟",
		downloadApp:'تحميل تطبيق UAQ الذكية ',
		shareData:'مشاركة عبر وسائل الاعلام الاجتماعية',
		govtUAQ:'حكومة أم القيوين',
		helpscreensloading: "يتم تحميل صفحة المساعدة",
		deptUAQ:'الحكومة الالكترونية',
		mobilereq:"الرجاء ادخال رقم الجوال",
		invalidMobile:"الرجاء ادخال رقم جوال صحيح",
		notAvailable:'مرفق الاتصال غير متوفر',
		contactInfo:'معلومات الاتصال لحكومة أم القيوين',
		shareEmail:'البريد الالكتروني',
		whatsApp:'واتساب',
		dataNotAvailable:'البيانات المنقولة غير متوفرة',
		//payment history
		viewMyPayment:"تاريخ الدفع",
		purchaseID:'رمز الشراء',
		purchaseStatus:'حالة الشراء',
		transID:'رمز المعاملة',
		transMSG:'رسالة المعاملة',
		transDate:'تاريخ المعاملة',
		amnt:'المبلغ',
		eDirhamFee:'رسوم الدرهم الالكتروني',
		transAmnt:'مبلغ المعاملة',
		transSuccessMSG:'تمت معالجة المعاملة بنجاح.',
		transFailMSG:'فشلت عملية الدفع',
		purchaseCompletedMSG:'انتهت',
		purchaseFailedMSG:'فشلت',
		receiptID:'رقم الايصال ',
		// my request new text
		paynowMyreq: 'ادفع الان',
		actLabel:"مفعَل",
		not_available:"غير متوفر",
		passwordHintText :"يلزم ان تحتوي كلمات المرور حروف كبيرة وحروف صغيرة و أرقام ورموز."
		
	};
	return arabic;
};

