exports.language = function() {
	var english = {
		appTitle : "Smart UAQ",
		english : "English",
		englishLF : "english",
		arabicLF: "arabic",
		news : "News",
		events : "Events",
		departments : "Departments",
		workingHour : "Working Hours",
		contactUs : "Contact Us",
		location : "Location",
		enterLandmark : "Enter Your Landmark",
		suggestions : "Category",
		comments : "Comments",
		firstName : "First Name",
		lastName : "Last Name",
		emailAddress : "Email Address",
		emailAddressConfirm : "Confirm Email Address",
		submit : "Submit",
		capSignIn : "SIGN IN",
		capRegister : "REGISTER",
		skip : "Skip",
		forgotPassword : "Forgot Password",
		userName : "Username",
		password : "Password",
		overviewCap : "OVERVIEW",
		theRulerCap : "THE RULER",
		crownPrinceCap : "CROWN PRINCE",
		crown:"Crown Prince",
		departmentCap : "DEPARTMENTS",
		favourite : "Favorite",
		happinessTitle : "How would you rate our services?",
		notificationTitle : "My Request Status",
		left : "Left",
		right : "Right",
		on : "On",
		off : "Off",
		send : "Send",
		registration : "Registration",
		fullName : "Full Name",
		nationality : "Nationality",
		dob : "Date of Birth",
		nationalId : "National Id",
		confirmPassword : "Confirm Password",
		mobile : "Mobile No",
		subscription : "Subscription",
		login : "Login",
		logout : "Logout",
		services : "Services",
		citizenCap : "INDIVIDUAL",
		businessCap : "BUSINESS",
		weatherCity : "Umm Al Quwain, U.A.E",
		weatherType : "Sunny",
		aboutUAQ : "About UAQ",
		feedback : "My Feedback",
		funeral : "UAQ Jnazah",
		home : "Home",
		mysuggestions : "My City",
		myservices : "My Services",
		edit : "edit",
		username : "username",
		menuDirectiion : "Menu Direction",
		notification : "Push Notification",
		dropbox: "Dropbox",
		mobile : "Registered Mobile Number",
		emiratesid : "Emirates Id",
		passport : "Passport Number",
		license : "License Number",
		submit : "Submit",
		mail : "Email Address",
		forgotUsername : "Forgot Username",
		individual : "Individual",
		establishment : "Establishment",
		open : "Open",
		loading : "Loading...",
		updating : "Updating...",
		cancel : "Cancel",
		registration : "Registration",
		individualCitizenLbl : "Individual - UAE Citizen",
		individualResidentLbl : "Individual - UAE Resident",
		individualGccCitizen : "Individual - GCC Citizen",
		individualGccResident : "Individual - GCC Resident",
		indivlVisitor : "Individual - Visitor",
		establishmentReg : "Establishment",
		fullname : "Full Name",
		fullNameHintText: "(as stated in the emirates id)",
		countryResidence : "Country of Residency",
		mobileNum : "Mobile Number 1",
		mobileNum2 : "Mobile Number 2",
		landlineNum : "Land line",
		establishNameAsStated : "Establishment Name",
		hintTextEstFullnamelbl: "(as Stated in the trade license)",
		dob : "Date of Birth",
		nationalId : "Emirates ID",
		nationalIdExpiry : "Emirates ID Expiry Date",
		confirmPassword : "Confirm Password",
		mobile : "Mobile No",
		emiratedId : "Emirates ID",
		chooseEmirates : "Emirates",
		emiratedIdFrontAttch : "Emirates ID Front",
		emiratedIdBackAttch : "Emirates ID Back",
		passportNum : "Passport Number",
		passportFrontAttach : "Passport First Page",
		accountDetailsSplit : "Account Details",
		credentialsSplit : "Credentials",
		idInformationSplit : "ID Information",
		passportInformatioinSplit : "Passport Information",
		familyBookSplit : "Family Book Information",
		hasFamilyBook : "I have a family book",
		fullNameBook : "Full name",
		townName : "Town Name",
		townNumber : "Town Number",
		familyNumber : "Family Number",
		tribeName : "Tribe Name",
		clanNumber : "Clan Number",
		issueDateBook : "Issuance Date",
		motherNameTxt : "Mother Name",
		motherFatherNameTxt : "Mother's Father",
		familyBookAttch : "Family Book ",
		fullnamePassport : "Full Name",
		hintTxtPassPostName : "(as stated in the passport)",
		visapagetxt : "Visa Page",
		
		
		passportResidentpage : "Passport Residency Page",
		subscription : "Subscription",
		subscriptionReg : "Subscribe To Receive Newsletter",
		CompleteRegProcess : "Complete registration process",
		OTPtxt : "OTP",
		sendAnotherOTP : "Resend another OTP",
		activateAccount : "User account Activation",
		activateAcounttxt : "Activate Account",
		individualUserTxt : "Individual",
		establishUserTxt : "Establishment",
		mobilenumberHinttxt : "Mobile Number",
		emiratesIDorPassport : "Emirates ID or Passport ID",
		tradeLicenceNumber : "Trade License Number",
		
		fullNameActivation : "Full Name",
		establishNameLbl : "Establishment Name",
		tradeLicenceLbl : "Trade License",
		signatureAttest : "Signatories Attestation",
		tradeLicenExpiryDate : "Trade License Expiry Date",
		tradeLicenseType : "Trade License Type",
		officePhoneLabel : "Office Phone",
		addressLabelen : "Address",
		websiteLabelEn : "Website",
		postBoxLabel : "Postbox",
		fileSizeExceed : "File Size Exceed",
		passwordValidate : "Your password strength is medium, enter only alpha-numeric characters",
		passwordValidate2: "Password must be 8 characters to 15 characters",
		passwordValidate3: "Password must contains capital,small,number and special character",
		userNameValid : "Special characters and space are not allowed. Only underscore and dot is allowed.",
		fullNameValid : "Special characters and numbers are not allowed.",
		weakTxt: "Strength : Weak",
		mediumTxt:"Strength : Medium",
		strongTxt : "Strength :Strong",
		plzCountryOfCitizenship : "Please Choose country of citizenship",
		plzCountryOfResidence : "Please choose country of resident",
		plzMobileNumber : "Please enter mobile number",
		plzOfficephone : "Please enter office phone number",
		plzEmailAddress : "Please enter email address",
		plzAddressEstablish : "Please enter address",
		plzWebsiteValue : "Please enter website address",
		plzUserName : "Please enter user name",
		plzPassword : "Please enter password",
		plzFullNameIndiv : "Please enter full name",
		plzEmiratesId : "Please enter emirates id",
		plzValidEmiratesId : "Please enter valid emirates id",
		plzChooseEmirates : "Please choose emirate",
		plzPostBox : "Please enter post box",
		plzPostBoxvalid : "Please enter valid post box number",
		plzTradeLicNum : "Please enter trade License number",
		plzTradeLicExpiry : "Please enter trade license expiry date",
		plzChooseTradeLicType : "Please choose trade license type",
		plzAttachTradeLic : "Please attach the trade license",
		plzAttachSignature : "Please attach the signature",
		plzEmiratesExpdate : "Please choose Emirates ID Expiry Date",
		plzChooseDOB : "Please choose date of birth",
		plzEmiratedIDfrontAttch : "please attach emirates id front page",
		plzEmiratesIdBackAttch : "please attach emirates id back page",
		plzPassportNum : "Please enter passport number",
		plzAttchPassportFront : "Please attach passport front page",
		plzPassportNamefull : "Please enter the full name as stated in the passport",
		plzPassportVisaPage : "Please attach passport visa page",
		plzEstablishName : "Please enter establishment name",
		plzAttchPassportResident : "Please attach passport residency page",
		plzFullnameBook : "Please enter full name as stated in the family book added",
		plzCooseEmirtesBook : "Please choose emirate for the family book added",
		plzTownNameBook : "Please enter town name for family book",
		plzTownNumber : "Please enter town number for family book",
		plzFamilyNumber : "please enter family number for family book",
		plzTribeName : "Please enter tribe name for family book",
		plzClanNumber : "please enter clan number for family book",
		plzChooseIssuedateBook : "please choose issue date for family book",
		plzMotherName : "Please enter mother name for family book",
		plzMotherFatherName : "Please enter mothers father name for family book",
		plzAttchFamilyBook : "Please attach family book",
		passwordMisMatch : "Password does not match",
		noRecordsFound : "No records found",
		uploadDocSuccess : "Document upload successful",
		enterValidEmail : "Please enter valid email address",
		emailNotMatch : "Email Address Confirmation doesn't match",
		enterValidMobile : "Please enter valid mobile number",
		enterValidlandline: "Please enter valid Land Line number",
		enterValidofficePhone : "Please enter valid office phone number",
		registrationSuccessful : "Registration successful",
		plzEmiratesOrPassportId : "please enter emirates id or passport number",
		yourAccountIsNotVerified : "your account is not verified, please try again later",
		plzEnterOTP : "Please enter code number that you've got on your mobile number",
		validateYouraccountOTP : "you have not activated your account",
		nationality : "Country of Citizenship",
		uploadDocfailed : "Document Upload failed",
		weatherCity : "Umm Al Quwain, U.A.E",
		weatherType : "Sunny",
		0 : "Tornado",
		1 : "Tropical storm",
		2: "Hurricane",
		3: "Severe thunderstorms",
		4: "Thunderstorms",
		5: "Mixed rain and snow",
		6: "Mixed rain and sleet",
		7: "Mixed snow and sleet",
		8: "Freezing drizzle",
		9: "Drizzle",
		10: "Freezing rain",
		11: "Showers",
		12: "Showers",
		13: "Snow flurries",
		14: "Light snow showers",
		15: "Blowing snow",
		16: "Snow",
		17: "Hail",
		18: "Sleet",
		19: "Dust",
		20: "Foggy",
		21: "Haze",
		22: "Smoky",
		23: "Blustery",
		24: "Windy",
		25: "Cold",
		26: "Cloudy",
		27: "Mostly cloudy",
		28: "Mostly cloudy",
		29: "Partly cloudy",
		30: "Partly cloudy",
		31: "Clear",
		32 : "Sunny",
		33 : "Fair",
		34 : "Fair",
		35 : "Mixed rain and hail",
		36 : "Hot",
		37 : "Isolated thunderstorms",
		38 : "Scattered thunderstorms",
		39 : "Scattered thunderstorms",
		40 : "Scattered showers",
		41 : "Heavy snow",
		42 : "Scattered snow showers",
		43 : "Heavy snow",
		44 : "Partly cloudy",
		45 : "Thundershowers",
		46 : "Snow showers",
		47 : "Isolated thundershowers",
		3200 : "not available",
		
		aboutUAQ : "About UAQ",
		// feedback : "Feedback",
		home : "Home",
		myservices : "My Request",
		edit : "edit",
		menuDirection : "Menu Direction",
		notification : "Push Notification",
		mobile : "Registered Mobile Number",
		emiratesid : "Emirates Id",
		passport : "Passport Number",
		license : "License Number",
		submit : "Submit",
		mail : "Email Address",
		forgotUsername : "Forgot Username",
		individual : "Individual",
		establishment : "Establishment",
		sendMail : "Send Mail",
		mailAccountMsg : "Email account not available.Please check your email account settings.",
		open : "Open",
		webURLMsg : "Unable to open the website.",
		enterUserName : "Enter UserName",
		enterEmiratesId : "Enter Emirates Id",
		passportNumber : "Enter Passport Number",
		mobileNumber : "Enter Mobile Number",
		licenseNumber : "Enter License Number",
		mailId : "Enter a proper email address",
		enterFirstName : "Enter First Name",
		enterLastName : "Enter Last Name",
		// submitFeedback : "Submit Feedback", - not used now... >NIKUNJ
		forgetPassword : "Forget Password",
		invalidmail : "Invalid Email Id",
		government : "Department of e-Government",
		enterComments : "Enter Comments",
		submitRating : "Thanks for rating our services",
		submitThanks : "Thanks for submitting your feedback",
		ruler : "Ruler",
		overView : "Overview",
		department : "Departments",
		favourite : "Favorites",
		description : "Description",
		submitTime : "Submitting Timing",
		serviceBeneficiary : "Service Beneficiary",
		requiredDocuments : "Required Documents",
		procedures : "Procedures",
		servicesFees : "Services Fees",
		startService : "Start Service",
		uaqJnazah : "UAQ Jnazah",
		plzEnterUserName : "Please enter username",
		plzEnterPassword : "Please enter password",
		youAccountisActive : "Your account is active, Please login",
		welcomeGuest : "Welcome",
		proApplicationFee : "Proceed to Application Fee Payment",
		procServiceFeep : "Proceed to Service Fee Payment",
		resubmit : "Resubmit",
		proReviewer : "Proceed to Reviewer",
		subNOC : "Submit NOC",
		subLicense : "Submit License",
		toissueSiteplan : "To Issue Site Plan", // to do arabic
		addFavourites : "Added to Favorites",
		removeFavourites : "Removed from Favorites",
		dismiss : "Dismiss",
		view : "View",
		generic : "About UAQ",
		device_regi_error : "An error occurred while sending device information to server, try again later",
		internet_err : "Internet connection is required.",
		zero_val : "0",
		no_details_found : "No details found.",
		contactsCustomerService : "Contacts Customer service",
		serviceRequestForm : "Service request from:",
		no_notification : "No notifications available right now!",
		exitConfirm : "Are you sure you want to exit the application ?",
		welcome : "Welcome",
		proApplicationFee : "Proceed to Application Fee Payment",
		procServiceFeep : "Proceed to Service Fee Payment",
		resubmit : "Resubmit",
		proReviewer : "Proceed to Reviewer",
		subNOC : "Submit NOC",
		subLicense : "Submit License",
		valid_last_name : "Last name should contain only alphabets.",
		valid_first_name : "First name should contain only alphabets.",
		login_access_eServices : "Please login before accessing your eServices notification messages.",
		suggestion_sent_failed : "Sorry, your suggestion has not been sent successfully. Please try again later",
		suggestion_sent : "Your suggestion has been sent successfully.",
		photo_uploaded : "Image uploaded successfully.",
		photo_upload_failed : "Photo uploading is failed.",
		blank_suggestion : "Please select a Category.",
		blank_comment : "Please enter your Comments.",
		valid_email_err : "Please enter a valid email address.",
		fname_req : "Please enter your First Name.",
		lname_req : "Please enter your Last Name.",
		email_req: "Please enter your Email address.",
		shareTwitterSuccess : "Successfully Tweeted on Twitter",
		duplicateMessage : "Already tweeted on Twitter",
		shareTwitterFail : "Unable to tweet on twitter. Please try again later",
		invalidMobile : "Mobile Number contains illegal characters. Only numbers are allowed",
		invalidEmiratesId:"Please enter 15 digits of Emirates id",
		mobileLength : "Please enter 10 digits mobile no.",
		allowAlphabets : "Only alphabets are allowed",
		facebook : "Facebook",
		twitter : "Twitter",
		share : "Share?",
		mail : "Email Address",
		mail_forgotUsername: "Email Address",
		ramadan : "Ramadan",
		viewMore : "View More",  // It is used in my reqeuest also dont remove it
		validateHintText : "Please enter either an emirates ID or a passport number",
		fbShare : "Share on Facebook",
		twitterShare : "Twitter Share",
		submittedRating : "You have already rated our application. Thank you for your feedback",
		viewMore : "View More",
		comingSoon : "Coming soon",
		reminder : "Reminder",
		or : "OR",


		arabic : "عربي",
		back : "Back",
		changeLanguage : "Change",
		call : "Phone Call",
		callConformAlert : 'Are you sure you want to make a call to',
		noCallAlert : 'Phone call service not available',
		ok : "OK",
		serviceError : 'The service is currently unavailable. Please try again later.',
		doneTitle : "Done",
		error : 'Error',
		language : "Change Language",
		noInternet : "No internet connection",
		networkError : "Network Error",
		preferMenuDirection : "Please select the direction preference of your menu",
		not_reg_push_error : "You are not registered for receiving push notification, Please try again or restart the app.",
		push_subscribe_success : "Push notification is subscribed successfully",
		push_unsubscribe_success : "Push notification is unsubscribed successfully.",
		suggestionPicLimit : "You can't send more than one attachments.",
		leave_from_suggestion : "Do you want to leave without sending suggestion?",

		indivlVisitor : "Individual - Visitor",
		fullNameHintText : "(as stated in the emirates id)",
		passportInformatioinSplit : "Passport Information",
		hintBookFullname : "(as stated in the family book)",

		cameraNotAvail : "Camera not available",
		useCamera : "Use camera",
		selectFromGallery : "Select from gallery",
		attachMedia : "Attach media",
		cameraNotAccess : "This app does not have access to your camera",
		camera : "Camera",
		actionBtn : "Action",
		proCardRequest : "PRO Card Request",
		landDemarkation : "Land Demarcation",
		extenGrandLand : "Extension Of Grand land",
		addLand : "Add Land",
		country : "Nationality",

		shareFBSuccess : "Shared on facebook Successfully",
		facebookCancel : "Facebook sharing is cancelled",
		shareFBFail : "Unable to share on facebook. Please try again later",
		
        photoupload_info : "Upload a photo by clicking on (+) button.", 

		ok : "OK",
		yes:"Yes",
		no:"No",
		skip_login_step:"Do you want to skip the login action.?",
		
		servicePayment : "Payment Location",
		serviceAmount : "Amount",
		serviceDescription : "Description",
		location_not_determined:"Your location could not be determined, please try again.",
		mobileNo:"Mobile Number",
		turn_on_location_service:"Please turn on your device Location service from system settings.",
		error_loading_eService_page:"An error occurred while loading Service page.",
		// Terms and Condtion
		agreetoTermsCond : "I Agree To The Terms & Conditions",
		plzAgreeTheTerms : "Please Agree The Terms & Conditions",
		termsAndCondition : "Terms & Conditions",
		accept : "Accept",
		decline : "Decline",
		termsPersonaldata:"Personal Data collected are:",
		termsPersonaldata1:"·         Full Name",
		termsPersonaldata2:"·         Personal details",
		termsPersonaldata3:"·         Email Address",
		termsPersonaldata4:"·         Mobile Number",
		termsPersonaldata5:"·         Trade license information(Register as an establishment)",
		termsPersonaldata6:"·         Geolocation",
		termsPersonalDetails:"The personal details are collected upon registration or while using Feedback or My Suggestions services provided by the SmartUAQ app and can be used to apply for the services provided by the application",
		termsDataControler : "Data Controller and Owner",
		termsDataContolerDesc : "The Services are operated by Umm Al Quwain eGovernment Department, Al Amiri Court, Umm Al Quwain, United Arab Emirates.Umm Al Quwain Government is the data controller for the Personal Data collected, processed, used disclosed or transferred in connection with the Services.",
		termsDataCollection : "Types of Data collected",
		termsDataCollectionDesc : "The Personal Data may be freely provided by the User, unless stated otherwise, serves to identify Users and remember their preferences, for the sole purpose of providing the service required by the User.",
		termsMethodOfProcess : "Methods of processing",
		termsMethodProcessDes : "The Data Controller processes the Data of Users in a proper manner and shall take appropriate security measures to prevent unauthorized access, disclosure, modification, or unauthorized destruction of the Data.",
		termsPlace : "Place",
		termsPlaceDes : "The Data is processed at the Data Controller's operating offices and in any other places where the parties involved with the processing are located.",
		termsRetentionTime : "Retention time",
		termsRetentionTimeDes : "The Data is kept for the time necessary to provide the service requested by the User, or stated by the purposes outlined in this document.",
		termsUseCollectionData : "The use of the collected Data",
		termsUseCollectionDataDes : "The Data concerning the User is collected to allow the Owner to provide its services, as well as for the following purposes: Location-based interactions.",
		termsLegalAction : "Legal action",
		termsLegalActionDes : "The User declares to be aware that the Data Controller may be required to reveal personal data upon request of public authorities.",
		termsLogmaintain : "System Logs and Maintenance",
		termsLogmaintainDes : "For operation and maintenance purposes, this Application and any third party services may collect files that record interaction with this Application (System Logs).",
		termsInformationNotContain : "Information not contained in this policy",
		termsInformationNotContainDes : "More details concerning the collection or processing of Personal Data may be requested from the Data Controller at any time. Please see the contact information +9716764100",
		termsUAQGovt : "The Umm Al Quwain eGovernment Department will not disclose personal information to third parties, except as provided below:",
		termsUAQGovtDes1 : "- When required to do so by law",
		termsUAQGovtDes2 : "- In connection with any legal proceedings.",
		termsChPrivacy : "Changes to this privacy policy",
		termsChPrivacyDes : "The Data Controller reserves the right to make changes to this privacy policy at any time by giving notice to its Users.",
		termsNotes : "*User should not provide any misleading false information during registration. Should this occur the Umm AL Quwian government has the right to take legal action against the individual or establishment",
		next:"Next",
		help:"App Tips",
		helpscreensloading: "Help screens are loading...",
		end:"End",
		shareapp:"Share App?",
		downloadApp:'Download the Smart UAQ App :',
		shareData:'Sharing via Social Media',
		govtUAQ:'GOVERNMENT OF UMM ALQUWAIN',
		mobilereq:"Please enter Mobile Number.",
		invalidMobile:"Please enter valid mobile number.",
		deptUAQ:'Department of E-Government',
		notAvailable:'Call facility is not available',
		contactInfo:'UAQ Contact Info',
		shareEmail:'Email',
		whatsApp:'What`s App',
		dataNotAvailable:'Translated data is not available',
		//payment history
		viewMyPayment:"Payment History",
		purchaseID:'Purchase ID:',
		purchaseStatus:'Purchase Status:',
		transID:'Transaction ID: ',
		transMSG:'Transaction Message:',
		transDate:'Transaction Date:',
		amnt:'Amount:',
		eDirhamFee:'eDirham Fees:',
		transAmnt:'Transaction Amount:',
		transSuccessMSG:'Transaction was processed successfully.',
		transFailMSG:'Payment failed.',
		purchaseCompletedMSG:'Completed',
		purchaseFailedMSG:'Failed',
		receiptID:'Receipt Number: ',
		// my request new text
		paynowMyreq: 'Pay Now',
		actLabel:"ACTIVE",
		not_available:"Not Available",
		passwordHintText : "Passwords must have at least uppercase letters, lowercase letters, numbers and symbols."
	};
	return english;
};
